---
# gleich diese Datei in einem Ordner mit Namen der Aufgabe abspeichern!
date: 2026-09-29  # DATUM AKTUALISIEREN!
draft: false   # ACHTUNG DRAFT STEHT AUF TRUE!
title:  muenzwurf  # HIER TITEL DES POSTS EINGEBEN.
execute: 
  eval: true 
  cache: true
highlight-style: arrow 
toc: true
number-sections: true


categories:
- probability  # ENTER CATEGORIES HERE

---





# Aufgabe 

Fünf Studierende unterhalten sich, wie man einen dreifachen Münzwurf mit dem Ergebnis von §X=3$ Treffern verstehen kann.
Welche Aussage ist richtig bzw. passt am besten?

A) Wirft man die Münze drei Mal, so gibt es 4 verschiedene Ergebnisse (0 bis 3 Treffer), die alle gleich wahrscheinlich sind. Aber nur ein Ergebnis ist gesucht, nämlich 3 von 3 Treffern. Also ist die Wahrscheinlichkeit 1/4,  25 %.
B) Man kann einfach einen Computer fragen, z. B. R mit `dbinom(x = 3, size = 3, prob = 1/2)`, da kommt ungefähr 10 % raus.
C) Wirft man die Münze drei Mal, so gibt es 8 Ergebnisse, die alle gleich wahrscheinlich sind. Aber nur ein Ergebnis ist gesucht, nämlich 3 von 3 Treffern. Also ist die Wahrscheinlichkeit 1/8, ca. 12,5 %.
D) Einfach die Zahlen in die Formel eintragen: $\left(\frac{1}{2}\right)^3 = \left(\frac{1}{2^3}\right) = \left(\frac{1}{8}\right)$
E) Wirft man die Münze drei Mal, so sind die Würfe nicht wirklich unabhängig: Nach zwei Treffern in Folge wird ein dritter Treffer unwahrscheinlicher, weil sich die Serie "ausgleichen" muss. Deshalb ist die Wahrscheinlichkeit für drei Treffer in Folge kleiner als $(1/2)^3$, nämlich nur ca. 6 %.



Hinweise:
ch 
- Gehen Sie von einer fairen Münze aus und von Unabhängigkeit der Würfe.
- Beachten Sie die üblichen [Hinweise](https://datenwerk.netlify.app/hinweise) des Datenwerks.


</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>











# Lösung 


**Richtig ist C).** Bei drei Würfen gibt es $2^3 = 8$ gleich wahrscheinliche Ergebnisse (KKK, KKZ, KZK, ..., ZZZ), von denen genau eines (KKK) drei Treffer liefert. Also ist $P(X=3) = 1/8 = 12{,}5,%$.

Warum die übrigen Aussagen nicht tragen:

- A) verwechselt die Anzahl der möglichen Trefferzahlen (0 bis 3, also 4 Werte) mit der Anzahl der gleich wahrscheinlichen Elementarereignisse (8). Die vier Trefferzahlen sind wegen der Binomialverteilung nicht gleich wahrscheinlich, daher ist $1/4$ falsch.

- B) wählt zwar den richtigen R-Befehl, gibt das Ergebnis aber ungenau wieder: dbinom(x = 3, size = 3, prob = 1/2) liefert exakt $1/8 = 12{,}5,%$, nicht nur "ungefähr 10 %".

- D) rechnet zwar korrekt ($1/8$), erklärt aber nicht, warum diese Rechnung die gesuchte Wahrscheinlichkeit ist: Es fehlt der Bezug zur Unabhängigkeit der Würfe (Multiplikationssatz $P(A\cap B\cap C)=P(A)\cdot P(B)\cdot P(C)$) sowie die Erkenntnis, dass für genau 3 Treffer der Binomialkoeffizient $\binom{3}{3}=1$ wegfällt. Bei einer anderen Trefferzahl (z. B. 2 von 3) würde die bloße Formel $p^k$ ohne Binomialkoeffizient ein falsches Ergebnis liefern.

- E) verletzt die im Aufgabentext ausdrücklich vorausgesetzte Unabhängigkeit der Würfe: Das ist der klassische Spielerfehlschluss (Gambler's Fallacy). Da die Münze kein "Gedächtnis" hat, bleibt die Wahrscheinlichkeit für Kopf bei jedem Wurf konstant $1/2$, unabhängig vom Ausgang der vorherigen Würfe.
