---
exname: tidydata1
extype: schoice
exsolution: 10000
exshuffle: no
categories:
- datawrangling
- tidy
- schoice
date: '2023-03-27'
slug: tidydata1
title: tidydata1

---




```{r libs, include = FALSE}
library(tidyverse)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = TRUE,
                      message = FALSE,
                      fig.show = "hold")

options(mc.cores = parallel::detectCores())

```






# Aufgabe



Laden Sie die folgende Tabellen mit folgendem Befehl aus dem Paket `tidyverse`:



```{r}
table1_path <- "https://raw.githubusercontent.com/sebastiansauer/Lehre/main/data/tidy-table1.csv"
table1 <- read_csv(table1_path)
```



Insgesamt sollten Sie als folgende Tabellen in Ihrem `environment` verfügbar haben:

- table1
- table2
- table3
- table4
- table5

Welche der Tabellen ist in der Normalform? 





Answerlist
----------
* table1
* table2
* table3
* table4
* table5




</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung

Laden wir noch die übrigen Tabellen

```{r}
table2_path <- "https://raw.githubusercontent.com/sebastiansauer/Lehre/main/data/tidy-table2.csv"
table2 <- read_csv(table2_path)

table3_path <- "https://raw.githubusercontent.com/sebastiansauer/Lehre/main/data/tidy-table3.csv"
table3 <- read_csv(table3_path)

table4_path <- "https://raw.githubusercontent.com/sebastiansauer/Lehre/main/data/tidy-table4.csv"
table4 <- read_csv(table4_path)

table5_path <- "https://raw.githubusercontent.com/sebastiansauer/Lehre/main/data/tidy-table5.csv"
table5 <- read_csv(table5_path)
```


Betrachten wir alle fünf Tabellen:

```{r}
table1
table2
table3
table4
table5
```


Man sieht, dass nur Tabelle 1 "tidy" ist.

[Quelle](http://garrettgman.github.io/tidying/)




Answerlist
----------


* Wahr
* Falsch
* Falsch
* Falsch
* Falsch





---

Categories: 

- datawrangling
- tidy
- schoice

