---
# gleich diese Datei in einem Ordner mit Namen der Aufgabe abspeichern!
date: 2024-09-07  # HEUTIGES DATUM EINTRAGEN, nicht "today"
draft: FALSE   # ACHTUNG DRAFT STEHT AUF TRUE!
title: mtcars-easystats 
execute: 
  
  eval: true 
highlight-style: arrow 
cache: true
toc: true
number-sections: true
extype: string
exsolution: ""
exshuffle: no
categories:
- datawrangling  # ENTER CATEGORIES HERE
- tidyverse
- eda
- en
- mtcars

#bibliography: "/../../library-ses.bib"


---


```{r}
#| include: false

options(digits=2)
```



# Exercise




Provide an overview on the mtcars dataset using the R package easystats.





</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Solution


Starting R packages:

```{r}
library(easystats) 
library(tidyverse)  # comfort
```


Providing the dataset mtcars:

```{r}
data(mtcars)
```



Here are some descriptive statistics for the metric variables of the dataset:

```{r}
#| eval: false
describe_distribution(mtcars) 
```





```{r}
#| echo: false
describe_distribution(mtcars) |> 
  print_md()
```



What about statistics for the non-metric (nominal) variables (columns)?
Let's restrict the analysis to the columns vs, am, and  gear.

```{r}
data_tabulate(mtcars, select = c("vs", "am", "gear"))
```

