---
exname: post-regression-1
extype: schoice
exsolution: 64
exshuffle: no
categories:
- regression
- bayes
- post
- paper
date: '2022-12-09'
slug: Postvert-Regr-01
title: Postvert-Regr-01

---




```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```






# Exercise



Nach der Berechnung bzw. Schätzung der Modellparameter eines Regressionsmodells (mit Methoden der Bayes-Inferenz) 
erhält man u.a. auf den Prädiktorwert $x$ und die Modellparameter $\theta$ bedingte Wahrscheinlichkeiten $p$ für den Wert der AV, $y = k$,
oder anders gesagt für  $y = k|(X,\theta)$ 
(mit $\theta$ für die Modellparameter).


Betrachten Sie dazu folgende Aussage:


$Pr(y|x, \alpha, \beta, \sigma) = c$ 



Welche der Aussagen ist in diesem Zusammenhang *falsch*?


Answerlist
----------
* Das Regressionsmodell hat 3 Parameter.
* Das Regressionsmodell hat 1 Prädiktor (im Sinne von 1 Inputvariablen).
* $Pr(y = a |x = a', \beta_0, \beta_1, \sigma) > Pr(y = b|x = b', \beta_0, \beta_1, \sigma)$
* $\sum_{k = -\infty}^{+\infty} Pr(y = k|x_i, \alpha, \beta, \sigma) = 1$
* $Pr(y = k|x, \beta_0, \beta_1, \sigma) = p, \qquad p \in [0,1]$



</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Solution


Answerlist
----------


* Falsch. Das Modell hat tatsächlich drei zu schätzende Parameter: $\alpha, \beta, \sigma$.
* Wahr. Das Modell hat tatsächlich einen Prädiktor, $x_i$.
* Wahr. Die Aussage beahuptet, dass die Wahrscheinlichkeit für $y = a$ bei $x = a'$ größer ist als die Wahrscheinlichkeit für $y = b$ bei $x = b'$. Das ist nicht immer, d.h. für alle möglichen Werte von $y$ und $x$ zwangsläufig richtig. Wenn es nicht immer richtig ist ist die Aussage daher falsch.
* Wahr. Die Wahrscheinlichkeiten für alle möglichen $y$ für eine bestimmte Beobachtung summiert sich tatsächlich zu 1 auf.
* Wahr. Eine Wahrscheinlichkeit kann tatsächlich zwischen 0 und 1 liegen, wobei die Grenzen nur in Extremfällen vorkommen.




---

Categories: 

- regression
- bayes
- post

