---
exname: Var-vs-Stufe
expoints: 1
extype: schoice
exsolution: NA
categories:
- fopro
- researchdesign
- schoice
date: '2023-10-11'
slug: Var-vs-Stufe
title: Var-vs-Stufe

---




# Aufgabe

Für ein Forschungsprojekt hat ein Forschungsteam die Frage getestet, ob Personen, die einen animierten Graphen zu Auswirkungen von Stress gesehen haben danach eine höhere Motivation haben ihr Stresspensum anzugehen, als Personen, die einen statischen Graph gesehen haben. 
Dazu wurde jeweils in einem Fragebogen die Veränderungsbereitschaft auf das Stressniveau angepasst abgefragt, 
dann den jeweiligen Graphen gezeigt und danach dieselben Fragen wie davor nochmals gestellt.

Zur Auswertung wurde nun zu jeder der Fragen zur Veränderungsbereitschaft die Mittelwerte der Vor-sehen-des-Graphen-Gruppe von der Nach-sehen-des-Graphen-Gruppe abgezogen und diese Werte dann verglichen von dem animierten und dem statischen Graphen. 
Dabei konnte der gewünschten Effekt deutlich erkannt werden, hypothesenkonform.

Nun kommt dem Forschungsteam folgender Zweifel auf:

Oder wäre die animierte und die statische Graphdarstellung jeweils als einzelne Variable zu betrachten?




Hinweise:

- Orientieren Sie sich im Übrigen an den [allgemeinen Hinweisen des Datenwerks](https://datenwerk.netlify.app/hinweise).




Answerlist
----------
* Ja, es wäre richtig gewesen, die animierte und die statische Graphdarstellung jeweils als einzelne Variable zu betrachten.
* Nein, es wäre falsch gewesen, die animierte und die statische Graphdarstellung jeweils als einzelne Variable zu betrachten.
* Beide Sichtweisen sind möglich (entweder jeweils als einzelne Variable oder als ingesamt eine einzelne Variable)
* Auf Basis des dargestellten Forschungsdesigns ist diese Frage nicht zu beantworten




</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung



Eine Variable besteht aus mehreren Ausprägungen, auch als Stufen bezeichnet.

In diesem Fall ist die Variable "Art des Graphs" die UV und hat zwei Stufen: animiert und statisch.



Answerlist
----------


* Falsch
* Wahr
* Falsch
* Falsch





---

Categories: 

- fopro
- researchdesign
- schoice

