---
exname: lik2
extype: schoice
exsolution: 512
exshuffle: no
date: '2022-11-05'
slug: Likelihood2
title: Likelihood2

---




```{r libs, include = FALSE}
library(tidyverse)

```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```






# Exercise

Der Likelihood eines Datensatzes ist definiert als das Produkt der Likelihoods aller Beobachtungen:

$$\mathcal{L} = \prod_{i=1}^n \mathcal{L_i}$$

wobei die Beobachtungen bzw. ihre Likelihood als unabhängig angenommen werden: $\mathcal{L_i} \perp \mathcal{L_j}, \quad i \ne j$.

Je größer $n$,  desto ........ $\mathcal{L}$!

Füllen Sie die Lücke!

Answerlist
----------
* größer
* kleiner
* unabhängig voneinander
* keine Aussage möglich
* kommt auf weitere, hier nicht benannte Bedingungen an




</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Solution


Multipliziert man zwei (oder mehr) Anteile $p_i$ (Wahrscheinlichkeiten), 
$p \in [0,1]$, so ist das resultierende Produkt nicht größer als $p_i$.
Je mehr Anteile $p_i$ man multipliziert, desto kleiner (näher an Null, aber positiv) das resultierende Produkt.

*Beispiel*: Die Wahrscheinlichkeit, dass eine zufällig bestimmte ("gezogene") Person eine Frau ist, 
sei $p=1/2$. Die Wahrscheinlichkeit, 
dass unter Personen zwei Frauen sind, 
beträgt $p_2 = p\cdot p=1/4$ (unter der Annahme, dass die Ziehungen unabhängig sind).
Wir sehen: Je mehr Wahrscheinlichkeiten ("Anteile") man multipliziert,
desto kleiner (näher an Null) das resultierende Produkt.



Answerlist
----------
* Falsch
* Richtig
* Falsch
* Falsch
* Falsch





---

Categories: 

~

