---
# gleich diese Datei in einem Ordner mit Namen der Aufgabe abspeichern!
date: 2024-12-13
draft: FALSE   # ACHTUNG DRAFT STEHT AUF TRUE!
title: qm2-quiz-verteilungen  # HIER TITEL DES POSTS EINGEBEN.
execute: 
  
  eval: true 
highlight-style: arrow 
cache: true
toc: true
number-sections: true
extype: string
exsolution: ""
exshuffle: no
categories:
- qm2  # ENTER CATEGORIES HERE
- 2024
- distributions

bibliography: "../../library-ses.bib"

knitr:
  opts_chunk:
    out.width: "75%"

---





# Aufgabe 


**Geben Sie jeweils an, ob die Aussage richtig oder falsch ist.**



1. Die Zuordnung der Elementarereignisse eines Zufallsexperiments zu genau einer Zahl 
$\in \mathbb{R}$ nennt man Zufallsvariable. 
2. Wahrscheinlichkeitsverteilungen dienen dazu, den Realisationen einer Zufallsvariablen eine Wahrscheinlichkeit zuzuordnen. 
3. Die Funktion $f$, die den möglichen Realisationen $x_i$ der stetigen Zufallsvariablen $X$ die Eintrittswahrscheinlichkeiten zuordnet, heißt Wahrscheinlichkeitsfunktion. 
4. Die Verteilungsfunktion $F$ gibt die Wahrscheinlichkeit an, dass die diskrete Zufallsvariable $X$ eine Realisation annimmt, die kleiner oder gleich $x$ ist. 
5. Der Graph einer stetigen Funktion lässt sich eine durchgängige Kurve zeichnen. 
6. Bei *stetigen* Zufallsvariablen $X$ geht man von unendlich vielen Ausprägungen aus; die Wahrscheinlichkeit einer bestimmten Ausprägung ist Null: $Pr(X=x_j)=0, \quad j=1,...,+\infty$
7. Die Wahrscheinlichkeit bei $n=3$ Zügen $k=2$ Treffer zu erzielen, wenn die Trefferwahrscheinlichkeit bei jedem Zug $p=2/5$ ist, beträgt ca. 29%. 
8. Die Normalverteilung ist eine nicht-schiefe Verteilung. Sie verfügt über einen Parameter, $\mu$, der den Mittelwert angibt. 
9. Das 50%-Quantil der IQ-Verteilung liegt bei 100. 
10. Die Standardnormalverteilung hat einen Mittelwert von 0 und eine Standardabweichung von 0. 
11. Die z-Transformation ist definiert als $z = \frac{x-\mu}{\sigma}$, wobei $x$ die Realisation der Zufallsvariablen $X$ ist, $\mu$ der Mittelwert und $\sigma$ die Standardabweichung. 
12. Ein Beispiel für eine normalverteile Zufallsvariable ist die Körpergröße von Menschen eines bestimmten Geschlechts. 
13. Ein Beispiel für eine randlastig verteilte Zufallsvariable ist die Opferzahl kriegerischer Auseinandersetzungen. 
14. Ein Beispiel für eine randlastig verteilte Zufallsvariable ist die Anzahl von Treffern beim wiederholten Münzwurf. 



</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>











# Lösung 


1. Die Zuordnung der Elementarereignisse eines Zufallsexperiments zu genau einer Zahl 
$\in \mathbb{R}$ nennt man Zufallsvariable. *R*
2. Wahrscheinlichkeitsverteilungen dienen dazu, den Realisationen einer Zufallsvariablen eine Wahrscheinlichkeit zuzuordnen. *R*
3. Die Funktion $f$, die den möglichen Realisationen $x_i$ der stetigen Zufallsvariablen $X$ die Eintrittswahrscheinlichkeiten zuordnet, heißt Wahrscheinlichkeitsfunktion. *F*
4. Die Verteilungsfunktion $F$ gibt die Wahrscheinlichkeit an, dass die diskrete Zufallsvariable $X$ eine Realisation annimmt, die kleiner oder gleich $x$ ist. *R*
5. Der Graph einer stetigen Funktion lässt sich eine durchgängige Kurve zeichnen. *R*
6. Bei *stetigen* Zufallsvariablen $X$ geht man von unendlich vielen Ausprägungen aus; die Wahrscheinlichkeit einer bestimmten Ausprägung ist Null: $Pr(X=x_j)=0, \quad j=1,...,+\infty$
7. Die Wahrscheinlichkeit bei $n=3$ Zügen $k=2$ Treffer zu erzielen, wenn die Trefferwahrscheinlichkeit bei jedem Zug $p=2/5$ ist, beträgt ca. 29%. *R*
8. Die Normalverteilung ist eine nicht-schiefe Verteilung. Sie verfügt über einen Parameter, $\mu$, der den Mittelwert angibt. *F*
9. Das 50%-Quantil der IQ-Verteilung liegt bei 100. *R*
10. Die Standardnormalverteilung hat einen Mittelwert von 0 und eine Standardabweichung von 0. *F*
11. Die z-Transformation ist definiert als $z = \frac{x-\mu}{\sigma}$, wobei $x$ die Realisation der Zufallsvariablen $X$ ist, $\mu$ der Mittelwert und $\sigma$ die Standardabweichung. *R*
12. Ein Beispiel für eine normalverteile Zufallsvariable ist die Körpergröße von Menschen eines bestimmten Geschlechts. *R*
13. Ein Beispiel für eine randlastig verteilte Zufallsvariable ist die Opferzahl kriegerischer Auseinandersetzungen. *R*
14. Ein Beispiel für eine randlastig verteilte Zufallsvariable ist die Anzahl von Treffern beim wiederholten Münzwurf. *R*



