project:
  type: website
  output-dir: docs


website:
  title: "datenwerk"
  page-footer:
    border: true
    left: |
      Powered by [Quarto](https://quarto.org).
    center: |
      Sebastian Sauer, 2024
    # right: |
    #   [[{{< iconify octicon:heart-16 >}}]{style="color:#c96198;"} Sponsor](https://github.com/sponsors/mcanouil?o=esb).
  cookie-consent: false
  repo-branch: main
  repo-actions: [edit, issue]
  repo-url: https://github.com/sebastiansauer/Datenwerk
  navbar:
    right:
      - about.qmd
      - Hinweise.qmd
      - English.qmd
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/sebastiansauer/


format:
  html:
    theme: yeti
    css: styles.css
    code-tools: true 
    df-print: kable
    opts_chunk: 
      collapse: true
      out.width: "75%"
      fig.align: center
    
    
editor: source 

execute:
  freeze: auto
  warning: false
  cache: true


  # - bib/bib.bib
bibliography: "ses.bib"
csl: "apa7.csl"
  
  
