project:
  type: website

repo-url:

website:
  title: "datenwerk"
  repo-url: https://github.com/sebastiansauer/Datenwerk
  navbar:
    right:
      - about.qmd
      - Hinweise.qmd
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/sebastiansauer/


format:
  html:
    theme: yeti
    css: styles.css
    code-tools: false

editor: source 

execute:
  freeze: auto
  
  
