project:
  type: website

website:
  title: "datenwerk"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sebastiansauer/


format:
  html:
    theme: yeti
    css: styles.css

editor: source 

