project:
  type: website


website:
  title: "datenwerk"
  repo-url: https://github.com/sebastiansauer/Datenwerk
  navbar:
    right:
      - about.qmd
      - Hinweise.qmd
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/sebastiansauer/


format:
  html:
    theme: yeti
    css: styles.css
    code-tools: true 

editor: source 

execute:
  freeze: auto
  warning: false


  # - bib/bib.bib
bibliography: "/Users/sebastiansaueruser/Google Drive/Literatur/refmgt/library-ses.bib"
csl: "/Users/sebastiansaueruser/Google Drive/Literatur/refmgt/apa7.csl"
  
  
