---
exname: wrangle4
extype: schoice
exsolution: 1
exshuffle: no
categories:
- eda
- '2023'
- schoice
date: '2023-03-27'
slug: wrangle4
title: wrangle4

---




```{r libs, include = FALSE}
library(tidyverse)
library(testthat)
library(glue)
library(printr)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```






# Aufgabe



Welche Variante der folgenden Syntax-Beispiele ist richtig (formal korrekt)?






Answerlist
----------
* `filter(flights, month = 1, day = 1)`
* `filter(flights, day == 1)`
* `filter(month == 1, day == 1)`
* `filter(month = 1, day == 1)`
* `filter(flights, month == 1, day == 1)`



</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung



S. [hier](https://r4ds.had.co.nz/transform.html#filter-rows-with-filter)

Answerlist
----------




* Falsch
* Falsch
* Falsch
* Falsch
* Wahr




---

Categories: 

- eda
- '2023'
- schoice

