---
extype: string
exsolution: NA
exname: stan_glm1
expoints: 1
categories:
- probability
- bayes
date: '2022-11-05'
slug: stan_glm01
title: stan_glm01

---




```{r libs, include = FALSE}
library(tidyverse)
library(testthat)
library(glue)
library(printr)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = TRUE,
                      message = FALSE,
                      fig.show = "hold")
```






# Exercise



Gegeben dem folgenden Modell, geben Sie den Befehl mit `stan_glm()` an, um die Posteriori-Verteilung zu berechnen.

Likelihood:
$h_i \sim \mathcal{N}(\mu, \sigma)$

Prior für $\mu$:
$\mu \sim \mathcal{N}(0, 1)$

Prior für $\sigma$:
$\sigma \sim \mathcal{U}(0, 10)$



</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Solution

```{r eval = FALSE}
library(rstanarm)


model <-
  stan_glm(h ~ 1,
           prior_intercept = normal(0,1),
           prior_aux = exponential(0.1),
           daten = meine_Daten
  )
```




---

Categories: 

- probability
- bayes

