---
exname: regex01
expoints: 1
extype: string
exsolution: NA
categories:
- textmining
- regex
- string
date: '2023-10-17'
slug: regex01
title: regex01

---



```{r global-knitr-options, include=FALSE, message=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      fig.show = "hold")
```



# Aufgabe

Erstellen Sie einen Vektor mit den Namen aller CSV-Dateien eines beliebigen Ordners Ihres Computers.

Hinweise:

- Orientieren Sie sich im Übrigen an den [allgemeinen Hinweisen des Datenwerks](https://datenwerk.netlify.app/hinweise).





</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung




```{r}
library(tidyverse)
library(tidytext)
```


Einen Order auswählen:

```{r}
data_path <- "/home/sebastian/Dokumente/datasets"
```


Dateien als Strings einlesen:

```{r}
files_in_my_folder <- list.files(data_path)
files_in_my_folder
```



Dateien als Strings einlesen:

```{r}
files_in_my_folder <- list.files(data_path)
files_in_my_folder
```


Nur CSV-Dateien einlesen:

```{r}
csv_files <- list.files(path = data_path,
                        pattern = "\\.csv$")
csv_files
```






---

Categories: 

- textmining
- regex
- string

