---
exname: Verteilungen-Quiz-14
extype: schoice
exsolution: 10
exshuffle: no
categories:
- distributions
- Verteilungen-Quiz
- probability
- bayes
- paper

- qm2-pruefung
date: '2022-11-20'
slug: Verteilungen-Quiz-14
title: Verteilungen-Quiz-14

---





```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = TRUE,
                      message = FALSE,
                      fig.show = "hold")



```






# Exercise

Ist folgende Aussage $A$ wahr?

Beim Perzentilintervall (PI) werden "links" und "rechts" die gleiche Wahrscheinlichkeitsmasse
von einer Verteilung "abgeschnitten".

Answerlist
----------

* Ja
* Nein



</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Solution

Bei einem 95%-PI werden links und rechts jeweils (ca.) 2.5% der Wahrscheinlichkeitsmasse "abgeschnitten".

Aussage $A$ ist also wahr.

```{r echo=FALSE}
mosaic::xpnorm(c(-2,2), 0, 1)
```





Answerlist
----------





* Wahr
* Falsch





---

Categories: 

- distributions
- Verteilungen-Quiz
- probability
- bayes
- simulation

