---
extype: string
exsolution: NA
exname: rethink-3e1-7
expoints: 1
categories:
- bayes
- ppv
- probability
date: '2022-11-05'
slug: ReThink3m1
title: ReThink3m1

---



```{r libs, include = FALSE}
library(tidyverse)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      echo = TRUE,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      message = FALSE,
                      warning = FALSE,
                      out.width = "50%",
                      cache = FALSE)
```








# Exercise


Nehmen wir an, wir haben 8 (Wasser-)"Treffer" ($W=8$) bei 15 Würfen ($N=15$) erhalten (wieder im Globusversuch). Gehen Sie wieder von einer "flachen", also gleichverteilten, Priori-Verteilung aus.

Berechnen Sie die Posteriori-Verteilung und visualisieren Sie sie. Nutzen Sie die Gittermethode.



</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Solution


```{r post-vert-p}
p_grid <- seq(from = 0, to = 1, length.out = 1000)
prior <- rep(1, 1000)
likelihood <- dbinom(8, size = 15, prob = p_grid)
posterior <- likelihood * prior
posterior <- posterior / sum(posterior)

tibble(p = p_grid, posterior = posterior) %>%
  ggplot(aes(x = p, y = posterior)) +
 # geom_point() +
  geom_line() +
  labs(x = "Anteil Wasser (p)", y = "Posterior Density")

```





[Quelle](https://sr2-solutions.wjakethompson.com/bayesian-inference.html#chapter-3)




---

Categories: 

- bayes
- ppv
- probability

