---
exname: wrangle1
extype: schoice
exshuffle: 5
exsolution: 64
categories:
- eda
- datawrangling
- tidyverse
- dplyr
- schoice
date: '2023-03-27'
slug: wrangle1
title: wrangle1

---




```{r libs, include = FALSE}
library(tidyverse)
library(testthat)
library(glue)
library(printr)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```






# Aufgabe



Welche der folgenden Spalte ist *nicht* Teil des Datensatzes `flights` aus dem R-Paket `nycflights13`?


Alternativ können Sie den Datensatz [hier](https://vincentarelbundock.github.io/Rdatasets/csv/nycflights13/flights.csv) beziehen.
Hilfe zum Datensatz (Codebook) finden Sie [hier](https://vincentarelbundock.github.io/Rdatasets/doc/nycflights13/flights.html).








Answerlist
----------
* year 
* month   
* day 
* dep_time 
* sched_dep_time 
* estimated_dep_time 
* arr_time 
* sched_arr_time




</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung

Mit `?flights` oder `help(flights)` kann man Hilfe bekommen (wenn das entsprechende Paket geladen ist).

S. [hier](https://rdrr.io/cran/nycflights13/man/flights.html)

Answerlist
----------


* Falsch 
* Falsch   
* Falsch 
* Falsch 
* Falsch 
* Wahr 
* Falsch 
* Falsch





---

Categories: 

- eda
- datawrangling
- tidyverse
- dplyr
- schoice

