---
exname: Flex-vs-nichtflex-Methode3
extype: schoice
exsolution: 10000
exshuffle: yes
expoints: 1
categories:
- statlearning
- '2023'
- schoice
date: '2023-05-17'
slug: Flex-vs-nichtflex-Methode3
title: Flex-vs-nichtflex-Methode3

---




```{r libs, include = FALSE}
library(tidyverse)
library(testthat)
library(glue)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```






# Aufgabe

Algorithmen des statistischen Lernens lassen sich unterteilen in ihrer Flexibilität; es gibt mehr bzw. weniger flexible Algorithmen. 

Welche der folgenden Aussagen ist in diesem Zusammenhang korrekt?


Answerlist
----------
* Weisen die Fehler eine hohe Streuung auf ($\sigma^2 = Var(\epsilon)$), so schneidet eine flexiblere Methode tendenziell *schlechter* ab als eine weniger flexible Methode aufgrund der *hohen* Varianz in der Test-$MSE$.

* Weisen die Fehler eine hohe Streuung auf ($\sigma^2 = Var(\epsilon)$), so schneidet eine flexiblere Methode tendenziell *besser* ab als eine weniger flexible Methode aufgrund der *hohen* Varianz in der Test-$MSE$.

* Weisen die Fehler eine hohe Streuung auf ($\sigma^2 = Var(\epsilon)$), so schneidet eine flexiblere Methode tendenziell *besser* ab als eine weniger flexible Methode aufgrund der *geringen* Varianz in der Test-$MSE$.

* Weisen die Fehler eine hohe Streuung auf ($\sigma^2 = Var(\epsilon)$), so schneidet eine flexiblere Methode tendenziell *schlechter* ab als eine weniger flexible Methode aufgrund der *geringen* Varianz in der Test-$MSE$.

* Weisen die Fehler eine hohe Streuung auf ($\sigma^2 = Var(\epsilon)$), so schneidet eine flexiblere Methode tendenziell *schlechter* ab als eine weniger flexible Methode aufgrund der *hohen* Verzerrung in der Test-$MSE$.


</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung



Answerlist
----------


* Wahr
* Falsch
* Falsch
* Falsch
* Falsch





---

Categories: 

- statlearning
- '2023'
- schoice

