---
# gleich diese Datei in einem Ordner mit Namen der Aufgabe abspeichern!
date: 2024-12-13
draft: FALSE   # ACHTUNG DRAFT STEHT AUF TRUE!
title: qm2-quiz-inferenz  # HIER TITEL DES POSTS EINGEBEN.
execute: 
  
  eval: true 
highlight-style: arrow 
cache: true
toc: true
number-sections: true
extype: string
exsolution: ""
exshuffle: no
categories:
- qm2  # ENTER CATEGORIES HERE
- 2024
- inference

bibliography: "../../library-ses.bib"

knitr:
  opts_chunk:
    out.width: "75%"

---





# Aufgabe 


**Geben Sie jeweils an, ob die Aussage richtig oder falsch ist.**





1. Man kann die Zielarten der Statistik in drei Gruppen fassen: Beschreiben, Vorhersagen und Entscheiden. 
2. Die Deskriptivstatistik fasst eine Stichprobe zusammen (in eine Zahl, die die Stichprobe repräsentiert). 
3. Die Inferenzstatistik schließt von einer Stichprobe auf die Grundgesamtheit und ist daher frei von Ungewissheit. 
4. Kennzahlen einer Population nennt man auch eine Statistik. 
5. Um die Streuung einer Population zu benennen, wird in der Statistik häufig der griechische Buchstabe $\mu$ verwendet. 
6. Eine Forscherin testen zwei Varianten ihres Webshops hinsichtlich der mittleren Verweildauer auf der Seite. Sie geht davon aus, dass die Verweildauer in Variante 1 $\mu_{V1}$ höher ist als in Variante zwei  $\mu_{V2}$. Ihre Hypothese formalisiert sie richtigerweise so: $\mu_{V1} > \mu_{V2}$.
7. Ein Modell ist ein vereinfachtes Abbild der Wirklichkeit. 
8. Die Ungewissheit eines wissenschaftlichen Modells kann man in zwei Arten aufteilen: Ungewissheit zu den Koeffizienten und Ungewissheit zur Modellspezifikation. 
9. Der Grund für die Schwankungen der Modellparameter zwischen den Stichproben ist die Zufälligkeit des Stichprobenziehens. 
10. Die Grenzen eines Konfidenzintervall markieren einen Bereich plausibler Werte für einen Parameter. 
11. Die Berücksichtigung von Vorwissen zum Sachgegenstand wird vom Frequentismus als objektiv zurückgewiesen. 
12. Der zentrale Kennwert des Frequentismus heißt der *p-Wert*. 
13. Die Definition eines Konfidenzintervalls im Frequentismus lautet: "Der Konfidenzbereich, z.B. von 95%, repräsentiert den Anteil der Konfidenzintervalle bei sehr vielen (oder unendlich vielen) Wiederholungen des Experiments, die den echten Parameterwert enthalten würden." 
14. Die Definition eines Konfidenzintervalls im Bayes'schen Ansatz lautet: "Der Konfidenzbereich, z.B. von 95%, gibt die Wahrscheinlichkeit an, dass der wahre Parameterwert innerhalb des Intervalls liegt." 
15. Ein frequentistisches Konfidenzintervall macht keine Aussage zur Wahrscheinlichkeit eines Werts in der Population (eines Parameters). 
16. Ein Bayes'sches Konfidenzintervall macht keine Aussage zur Wahrscheinlichkeit eines Werts in der Population (eines Parameters). 
17. Der Bayes'sche Ansatz wird subjektiv genannt, weil er das Vorwissen eines Forschers berücksichtigt. 

</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>











# Lösung 




1. Man kann die Zielarten der Statistik in drei Gruppen fassen: Beschreiben, Vorhersagen und Entscheiden. *F*
2. Die Deskriptivstatistik fasst eine Stichprobe zusammen (in eine Zahl, die die Stichprobe repräsentiert). *R*
3. Die Inferenzstatistik schließt von einer Stichprobe auf die Grundgesamtheit und ist daher frei von Ungewissheit. *F*
4. Kennzahlen einer Population nennt man auch eine Statistik. *F*
5. Um die Streuung einer Population zu benennen, wird in der Statistik häufig der griechische Buchstabe $\mu$ verwendet. *F*
6. Eine Forscherin testen zwei Varianten ihres Webshops hinsichtlich der mittleren Verweildauer auf der Seite. Sie geht davon aus, dass die Verweildauer in Variante 1 $\mu_{V1}$ höher ist als in Variante zwei  $\mu_{V2}$. Ihre Hypothese formalisiert sie richtigerweise so: $\mu_{V1} > \mu_{V2}$. *R*
7. Ein Modell ist ein vereinfachtes Abbild der Wirklichkeit. *R*
8. Die Ungewissheit eines wissenschaftlichen Modells kann man in zwei Arten aufteilen: Ungewissheit zu den Koeffizienten und Ungewissheit zur Modellspezifikation. *R*
9. Der Grund für die Schwankungen der Modellparameter zwischen den Stichproben ist die Zufälligkeit des Stichprobenziehens. *R*
10. Die Grenzen eines Konfidenzintervall markieren einen Bereich plausibler Werte für einen Parameter. *R*
11. Die Berücksichtigung von Vorwissen zum Sachgegenstand wird vom Frequentismus als objektiv zurückgewiesen. *F*
12. Der zentrale Kennwert des Frequentismus heißt der *p-Wert*. *R*
13. Die Definition eines Konfidenzintervalls im Frequentismus lautet: "Der Konfidenzbereich, z.B. von 95%, repräsentiert den Anteil der Konfidenzintervalle bei sehr vielen (oder unendlich vielen) Wiederholungen des Experiments, die den echten Parameterwert enthalten würden." *R*
14. Die Definition eines Konfidenzintervalls im Bayes'schen Ansatz lautet: "Der Konfidenzbereich, z.B. von 95%, gibt die Wahrscheinlichkeit an, dass der wahre Parameterwert innerhalb des Intervalls liegt." *R*
15. Ein frequentistisches Konfidenzintervall macht keine Aussage zur Wahrscheinlichkeit eines Werts in der Population (eines Parameters). *R*
16. Ein Bayes'sches Konfidenzintervall macht keine Aussage zur Wahrscheinlichkeit eines Werts in der Population (eines Parameters). *F*
17. Der Bayes'sche Ansatz wird subjektiv genannt, weil er das Vorwissen eines Forschers berücksichtigt. *R*



