---
extype: string
exsolution: NA
exname: ungewiss-arten-regr
expoints: 1
tags:
- inference
- lm
categories:
- qm2
- qm2-thema01
- ws22
date: '2022-07-10'
slug: ungewiss-arten-regr
title: ungewiss-arten-regr

---


# Exercise


Eine statistische Analyse, wie eine Regression, ist mit mehreren Arten an Ungewissheit konfrontiert. Zum einen gibt es die *Ungewissheit in den Modellparametern*. Für die Regression bedeutet das: "Liegt die Regressionsgerade in "Wahrheit" (in der Population) genauso wie in der Stichprobe, sind Achsenabschnitt und Steigung in der Stichprobe also identisch zur Popuation?". Zum anderen die *Ungewissheit innerhalb des Modells*. Auch wenn wir die "wahre" Regressionsgleichung kennen würden, wären (in aller Regel) die Vorhersagen trotzdem nicht perfekt. Auch wenn wir etwa wüssten, wieviel Klausurpunkte "in Wahrheit" pro Stunde Lernen herausspringen (und wenn wir den wahren Achsenabschnitt kennen würden), so würde das Modell trotzdem keine perfekten Vorhersagen zum Klausurerfolg liefern. Vermutlich fehlen dem Modell wichtige Informationen etwa zur Motivation der Studentis.

Vor diesem Hintergrund, betrachten Sie folgendes statistisches Modell,
das mit den Methoden der Bayes-Statistik berechnet wurde:

```{r}
data(mtcars) 
library(rstanarm) 
lm1 <- stan_glm(mpg ~ hp, data = mtcars,
                refresh = 0)  # um nicht zu viel R-Ausgabe zu erhalten

print(lm1)
```


Für den Prädiktor `hp` ist das Regressionsgewicht angegeben unter der Spalte `median`.
Dieser Wert entspricht der Punktschätzung in der Population und ist identisch zum Regressiongewicht der Stichprobe.

Die Spalte `MAD_SD` gibt den Standardfehler zur Schätzung des Koeffizienten (der entsprechenden Zeile) wieder.  


a) Welche Zahl kennzeichnet die Ungewissheit des Modells zum Achsenabschnitt?
b) Welche Zahl kennzeichnet die Ungewissheit des Modells zum Regressionsgewicht?
c) Welche Zahl(en) kennzeichnet/kennzeichnen die Ungewissheit des Modells gegeben der Modellparameter (die Ungewissheit innerhalb des Modells)?




</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Solution

a) 1.7
b) 0.0
c) 3.9 und auch dazu 0.5





---

Categories: 

- qm2
- qm2-thema01
- ws22

