---
# gleich diese Datei in einem Ordner mit Namen der Aufgabe abspeichern!
date: 2024-12-13
draft: FALSE   # ACHTUNG DRAFT STEHT AUF TRUE!
title: qm2-quiz-wskt  # HIER TITEL DES POSTS EINGEBEN.
execute: 
  
  eval: true 
highlight-style: arrow 
cache: true
toc: true
number-sections: true
extype: string
exsolution: ""
exshuffle: no
categories:
- qm2  # ENTER CATEGORIES HERE
- 2024
- probability

bibliography: "../../library-ses.bib"

knitr:
  opts_chunk:
    out.width: "75%"

---





# Aufgabe 


**Geben Sie jeweils an, ob die Aussage richtig oder falsch ist.**



1. Bei einem Zufallsexperiment ist der Ereignisraum unbekannt. 
2. Meim Würfelwurf ist $\Omega = \{ 1,2,3,4,5,6 \} = \{⚀, ⚁, ⚂, ⚃, ⚄, ⚅\}$ ein sinnvoller Ereignisraum. 
3. Jede einelementige Teilmenge von $\Omega$ heißt Elementarereignis.
4. Das leere Ereignis $\emptyset$ ist ein unmögliches Ereignis. 
5. Jede einelementige Teilmenge $\{\omega\}$ von $\Omega$ heißt *Elementarereignis*. 
6. Wird der Grundraum $\Omega$ vollständig in paarweis disjunkte Ereignisse zerlegt, so bilden diese Ereignisse ein vollständiges Ereignissystem. 
7. Die formallogische Konzeption von Wahrscheinlichkeit sieht Wahrscheinlichkeit als Erweiterung der formalen Logik. In der formallogischen Konzeption wird der Platz zwischen "falsch" (0) und "richtig" (1) durch die Wahrscheinlichkeit $0<p<1$ gefüllt. 
9.  Das Prinzip des unzureichenden Grundes) besagt, dass in Abwesenheit jeglicher Informationen, die bestimmte Ereignisse bevorzugen oder benachteiligen würden, alle möglichen Elementarereignisse als unterschiedlich wahrscheinlich angesehen werden sollten. 
10.  Die Wahrscheinlichkeit eines Ereignisses kann nicht negativ sein und nicht größer als 1. 
11. Man schreibt $C = A \cup B$ und liest: "C ist A geschnitten mit B". 
12. Beim Würfelwurf ist das Komplementärereignis zu "1" das Ereignis "6". 
13. Das Ereignis "1" und das Ereignis "6" sind disjunkt (beim Würfelwurf). 
14. Die Ereignisse "Zahl zwischen 1 und 3" und das Ereignis "gerade Zahl" sind disjunkt (beim Würfelwurf). 
15. Der allgemeine Additionssatz für Wahrscheinlichkeiten lautet: $P(A \cup B) = P(A) + P(B)$. 
16. Die auf B bedingte Wahrscheinlichkeit von A ist definiert als $P(A|B) = \frac{P(A \cap B)}{P(B)}$. 
17. Zwei Ereignisse sind (stochastisch) *unabhängig* voneinander, wenn die Wahrscheinlichkeit von $A$ *nicht* davon abhängt, ob $B$ der Fall ist. 
18. Der allgemeine Multiplikationssatz für Wahrscheinlichkeiten lautet: $P(A \cap B) = P(A) \cdot Pr(B)$. 



</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>











# Lösung 


1. Bei einem Zufallsexperiment ist der Ereignisraum unbekannt. *F*
2. Meim Würfelwurf ist $\Omega = \{ 1,2,3,4,5,6 \} = \{⚀, ⚁, ⚂, ⚃, ⚄, ⚅\}$ ein sinnvoller Ereignisraum. *R*
3. Jede einelementige Teilmenge von $\Omega$ heißt Elementarereignis. *R*
4. Das leere Ereignis $\emptyset$ ist ein unmögliches Ereignis. *R*
5. Jede einelementige Teilmenge $\{\omega\}$ von $\Omega$ heißt *Elementarereignis*. *R*
6. Wird der Grundraum $\Omega$ vollständig in paarweis disjunkte Ereignisse zerlegt, so bilden diese Ereignisse ein vollständiges Ereignissystem. *R*
7. Die formallogische Konzeption von Wahrscheinlichkeit sieht Wahrscheinlichkeit als Erweiterung der formalen Logik.In der formallogischen Konzeption wird der Platz zwischen "falsch" (0) und "richtig" (1) durch die Wahrscheinlichkeit $0<p<1$ gefüllt. *R*
9.  Das Prinzip des unzureichenden Grundes) besagt, dass in Abwesenheit jeglicher Informationen, die bestimmte Elementarereignisse bevorzugen oder benachteiligen würden, alle möglichen ElemnteraEreignisse als unterschiedlich wahrscheinlich angesehen werden sollten. *F*
10.  Die Wahrscheinlichkeit eines Ereignisses kann nicht negativ sein und nicht größer als 1. *R*
11. Man schreibt $C = A \cup B$ und liest: "C ist A geschnitten mit B". *F*
12. Beim Würfelwurf ist das Komplementärereignis zu "1" das Ereignis "6". *F*
13. Das Ereignis "1" und das Ereignis "6" sind disjunkt (beim Würfelwurf). *R*
14. Die Ereignisse "Zahl zwischen 1 und 3" und das Ereignis "gerade Zahl" sind disjunkt (beim Würfelwurf). *F*
15. Der allgemeine Additionssatz für Wahrscheinlichkeiten lautet: $P(A \cup B) = P(A) + P(B)$. *F*
16. Die auf B bedingte Wahrscheinlichkeit von A ist definiert als $P(A|B) = \frac{P(A \cap B)}{P(B)}$. *R*
17. Zwei Ereignisse sind (stochastisch) *unabhängig* voneinander, wenn die Wahrscheinlichkeit von $A$ *nicht* davon abhängt, ob $B$ der Fall ist. *R*
18. Der allgemeine Multiplikationssatz für Wahrscheinlichkeiten lautet: $P(A \cap B) = P(A) \cdot Pr(B)$. *F*


