---
exname: korr01
extype: schoice
exsolution: 64
exshuffle: no
categories:
- dyn
- eda
- association
- schoice
date: '2023-05-08'
slug: korr01
title: korr01

---




```{r libs, include = FALSE}
library(tidyverse)
library(MASS)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```






# Aufgabe

```{r out.width = "50%", warning=FALSE}
set.seed(42)
d <-
  mvrnorm(n = 600,
          mu = c(0, 0),
          Sigma = diag(2)
          ) %>% 
  as_tibble() 

ggplot(d) +
  aes(x = V1, y = V2) +
  geom_point()
```

Welcher Korrelationswert (Pearson) beschreibt die Korrelation in den Daten am besten?

Answerlist
----------
* $r = 1$
* $r = -1$
* $r = 0$
* $r = .8$
* $r = -.8$




</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung

C. Die Daten wurden aus unkorrelierten Populationen (jeweils normalverteilt) gezogen, also $\rho = 0$.

Hinweis: Griechische Buchstaben werden hier verwendet, um Variablen aus Populationen zu beschreiben (Parameter),
lateinische Buchstaben werden für Stichproben verwendet.

Answerlist
----------


* Falsch
* Falsch
* Wahr
* Falsch
* Falsch





---

Categories: 

- dyn
- eda
- association
- schoice

