---
# gleich diese Datei in einem Ordner mit Namen der Aufgabe abspeichern!
date: 2025-09-20
draft: false   # ACHTUNG DRAFT STEHT AUF TRUE!
title: interpret-ci2  # HIER TITEL DES POSTS EINGEBEN.
execute: 
  eval: true 
highlight-style: arrow 
cache: true
toc: true
number-sections: true


categories:
- inference  # ENTER CATEGORIES HERE


bibliography: "../../library-ses.bib"

knitr:
  opts_chunk:
    out.width: "75%"

---





# Aufgabe 

Welche der folgenden Aussagen zur Interpretation eines Populationsparameters (z.B. $\mu$) eines Konfidenzintervalls der Art `95% CI [182cm; 184cm]` ist richtig bzw. passt am besten?


> Würde man die Studie sehr oft wiederholen, würden 95% der entstehenden Konfidenzintervalle den wahren Wert beinhalten.


A) Passt nur zur Bayesianischen, nicht zur Frequentistischen Statistik
B) Passt nur zur Frequentistischen, nicht zur Bayesianischen Statistik
C) Passt sowohl zur Frequentistischen, als auch zur Bayesianischen Statistik
D) B) Passt weder zur Frequentistischen, noch zur Bayesianischen Statistik

Hinweise:


- Beachten Sie die üblichen [Hinweise](https://datenwerk.netlify.app/hinweise) des Datenwerks.


</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>











# Lösung 


B) Passt nur zur Frequentistischen, nicht zur Bayesianischen Statistik



