---
# gleich diese Datei in einem Ordner mit Namen der Aufgabe abspeichern!
date: 2024-11-12
draft: FALSE   # ACHTUNG DRAFT STEHT AUF TRUE!
title: exp1  # HIER TITEL DES POSTS EINGEBEN.
execute: 
  
  eval: true 
highlight-style: arrow 
cache: true
toc: true
number-sections: true
extype: string
exsolution: ""
exshuffle: no
categories:
- probability  # ENTER CATEGORIES HERE
- distributions
- paper

bibliography: "../../library-ses.bib"

knitr:
  opts_chunk:
    out.width: "75%"

---





# Aufgabe 


Die Expontentialverteilung ist eine häufig verwendete Verteilung in der Statistik. 
Sie kann verwendet werden, um Streuungen zu modellieren.

Welche der folgenden Aussagen zur Exponentialverteilung sind korrekt?

A. Die Exponentialverteilung ist eine stetige Verteilung.
B. Die Exponentialverteilung ist nur für nicht-negative Werte definiert.
C. Die Exponentialverteilung ist symmetrisch.
D. Die Exponentialverteilung hat nur einen Parameter.
E. Die Exponentialverteilung ist streng monoton fallend.





</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>











# Lösung 


A. Die Exponentialverteilung ist eine stetige Verteilung. RICHTIG
B. Die Exponentialverteilung ist nur für nicht-negative Werte definiert. RICHTIG
C. Die Exponentialverteilung ist symmetrisch. FALSCH
D. Die Exponentialverteilung hat nur einen Parameter. RICHTIG
E. Die Exponentialverteilung ist streng monoton fallend. RICHTIG


Hier ist ein Beispiel für eine Exponentialverteilung mit dem Parameterwert $\lambda = 0.1$:


```{r}
#|echo: false
library(teacherplot)
library(ggplot2)
p <- exp_plot(1/10) +
  theme_minimal()
p
```


