---
exname: Bootstrap1
extype: schoice
exsolution: 10000
exshuffle: yes
expoints: 4
categories:
- statlearning
- ds1
- schoice
date: '2023-05-17'
slug: Bootstrap1
title: Bootstrap1

---




```{r libs, include = FALSE}
library(tidyverse)
library(testthat)
library(glue)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```






# Aufgabe

Die Bootstrap-Methode ist eine beliebte numerische Methode im statistischen Lernen und in der Statistik allgemein. Welche der folgenden Aussagen zum Bootstrapping ist richtig?


Answerlist
----------
* Bootstrapping ist (u.a.) eine alternative Methode zur Kreuzvalidierung.
* Bootstrapping sollte nur bei normalverteilten Variablen verwendet werden.
* Bootstrapping basiert auf Ziehen ohne Zurücklegen.
* Bootstrapping sollte nur verwendet werden, wo gleichzeitig eine analytische (exakte) Methode bekannt ist.
* Bootstrapping sollte *nicht* verwendet werden, um Standardfehler zu schätzen.




</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung




Answerlist
----------


* Wahr
* Falsch
* Falsch
* Falsch
* Falsch





---

Categories: 

- statlearning
- ds1
- schoice

