---
exname: wskt-quiz03
extype: schoice
exsolution: 10
exshuffle: no
categories:
- quiz
- probability
- quiz1-qm2-ws23
- schoice
date: '2023-11-08'
title: wskt-quiz03

---




```{r global-knitr-options, include=FALSE, message=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = TRUE,  # ECHO IS FALSE!!!
                      message = FALSE,
                      fig.show = "hold")
```






# Aufgabe


Wirft man eine faire Münze 10-fach, so gilt $Pr(\text{10 mal Kopf}) = Pr(\text{10 mal Zahl}) > .01$.

Hinweise:

- Orientieren Sie sich im Übrigen an den [allgemeinen Hinweisen des Datenwerks](https://datenwerk.netlify.app/hinweise).


Answerlist
----------

* Falsch
* Wahr


</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung




```{r}
Kopf10 <- Zahl10 <- (1/2)^10
Kopf10
```

Diese Zahl ist kleiner .01:

```{r}
Kopf10 < .01
```



Answerlist
----------


* *Falsch*
* Wahr







---

Categories: 

- quiz
- probability
- quiz1-qm2-ws23
- schoice

