---
exname: NAME-OF-EXERCISE
extype: num
exsolution: r fmt(sol)
exshuffle: no
expoints: 1
categories:
- R
- unfertig
- buggy
- num
date: '2023-05-17'
slug: wf_set01
title: wf_set01

---






```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      cache = TRUE,
                      echo = TRUE,
                      message = FALSE,
                      fig.show = "hold")

library(tidyverse)
library(exams)
```






# Aufgabe

Berechnen Sie ein Workflow-Set mit Tidymodels. Halten Sie die Sache einfach.

Modellgleichung `mpg ~ hp, data = mtcars`.




</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung

## Setup

```{r}
library(tidymodels)
data(mtcars)
```


## Modelle

```{r}
mod_nn <- nearest_neighbor()
mod_lm <- linear_reg()
```


# Workflow

Resampling:

```{r}
rsmpl_boot <- boostrap(mtcars)
```


## Fitten






---

Categories: 

- R
- unfertig
- buggy
- num

