---
exname: lm-mario2
extype: num
exsolution: 49.25
exshuffle: no
expoints: 1
categories:
- R
- lm
- predict
- num
date: '2023-05-15'
slug: lm-mario2
title: lm-mario2

---








# Aufgabe


Sagen Sie den Verkaufspreis vorher für ein Spiel mit 3 Euro Versandkosten!








</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung

## Setup


```{r}
mariokart <- read.csv("https://vincentarelbundock.github.io/Rdatasets/csv/openintro/mariokart.csv")

library(tidyverse)
library(easystats)
```


## Regressionsgerade berechnen


```{r}
lm_mariokart <- lm(total_pr ~ ship_pr, data = mariokart)
lm_mariokart
```


"lm" wie *l*lineares *M*odell, also eine Gerade.


## Vorhersagen

Vorhersagen funktionieren mit dem Befehl `predict`.

```{r}
neues_spiel <-
  tibble(
    ship_pr = 3
  )

neues_spiel
```

Anstelle von  `tibble` können Sie auch `data.frame` verwenden.

```{r}
predict(lm_mariokart, neues_spiel)  # predicte mir den Verkaufspreis
```












---

Categories: 

- R
- lm
- predict
- num

