---
exname: variability01
extype: schoice
exsolution: 1
exshuffle: no
categories:
- variability
- basics
- schoice
date: '2023-02-02'
slug: variability01
title: variability01

---




```{r libs, include = FALSE}
library(tidyverse)
library(easystats)
library(ggpubr)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")

```






# Aufgabe

In welchem Datensatz, $x1, x2, x3, x4$, gibt es am meisten Variation?



```{r echo=FALSE}
set.seed(42)
d <- tibble(
  x1 = rnorm(10, mean = 0, sd = .1),
  x2 = rnorm(10, mean = 0, sd = 1),
  x3 = rnorm(10, mean = 0, sd = 10),
  x4 = rnorm(10, mean = 0, sd = 100),
)
```


Datensatz x1:

```{r}
d %>% 
  select(x1) %>% 
  display()
```

```{r echo=FALSE}
gghistogram(d, x = "x1")
```


Datensatz x2:

```{r}
d %>% 
  select(x2) %>% 
  display()
```


```{r echo=FALSE}
gghistogram(d, x = "x2")
```




Datensatz x3:

```{r}
d %>% 
  select(x3) %>% 
  display()
```


```{r echo=FALSE}
gghistogram(d, x = "x3")
```






Datensatz x4:

```{r}
d %>% 
  select(x4) %>% 
  display()
```


```{r echo=FALSE}
gghistogram(d, x = "x4")
```



Answerlist
----------
* A
* B
* C
* D





</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung


Answerlist
----------


* Falsch
* Falsch
* Falsch
* Wahr






---

Categories: 

- variablity
- basics
- schoice

