---
extype: string
exsolution: NA
exname: sim-prior
expoints: 1
date: '2022-11-05'
slug: Sim-Prior
title: Sim-Prior

---




```{r libs, include = FALSE}
library(tidyverse)
library(testthat)
library(glue)
library(printr)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = TRUE,
                      message = FALSE,
                      fig.show = "hold")
```






# Exercise



Gegeben dem folgenden Modell, simulieren Sie Daten aus der Prior-Verteilung (Priori-Prädiktiv-Verteilung).

Likelihood:
$h_i \sim \mathcal{N}(\mu, \sigma)$

Prior für $\mu$:
$\mu \sim \mathcal{N}(0, 1)$

Prior für $\sigma$:
$\sigma \sim \mathcal{U}(0, 10)$



</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Solution

```{r}
library(tidyverse)

n <- 1e4


sim <- tibble(
  mu = rnorm(n = n),  # Default-Werte sind mean=0, sd = 1
  sigma = runif(n = n, 0, 10)) %>%
  mutate(
    y = rnorm(n = n, mean = mu, sd = sigma))

ggplot(sim, aes(x = y)) +
  geom_density() +
  labs(x = "y", y = "Dichte") +
  theme_minimal()
```




---

Categories: 

~

