---
exname: nullhyp-beispiel
extype: schoice
exsolution: 10000
exshuffle: no
categories:
- nullhypothesis
- significance
- inference
date: '2022-12-14'
slug: Nullhyp-Beispiel
title: Nullhyp-Beispiel

---




```{r libs, include = FALSE}
library(tidyverse)

```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```






# Exercise

Welches der folgenden Beispiele ist *kein* Beispiel für eine Nullhypothese?

Answerlist
----------
* $\beta_1 <= 0$
* $\mu_1 = \mu_2$
* $\mu_1 = \mu_2 = ... = \mu_k$
* $\rho = 0$
* $\pi_1 = \pi_2$




</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Solution


Answerlist
----------


* Wahr
* Falsch
* Falsch
* Falsch
* Falsch





---

Categories: 

- nullhypothesis
- significance
- inference

