---
exname: bayes-ziel1
extype: schoice
exsolution: 1
exshuffle: no
categories:
- regression
- bayes
date: '2022-12-09'
title: Bayes-Ziel1

---




```{r libs, include = FALSE}
library(tidyverse)

```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```






# Exercise

Was ist *nicht* Ziel oder Gegenstand einer Bayes-Analyse?

Answerlist
----------
* updating beliefs
* quantifying uncertainty
* including prior knowledge of the domain, possibly of subjective nature
* drawing inferential conclusions solely based on the likelihood




</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Solution

Bei der Bayes-Analyse werden die Schlussfolgerungen nicht nur auf Basis des Likelihoods gezogen (im Gegensatz zum Frequentistischen Ansatz).

Answerlist
----------


* Falsch
* Falsch
* Falsch
* Wahr






---

Categories: 

- regression
- bayes

