---
# gleich diese Datei in einem Ordner mit Namen der Aufgabe abspeichern!
date: 2024-07-02
draft: ture   # ACHTUNG DRAFT STEHT AUF TRUE!
title: pvalue1  # HIER TITEL DES POSTS EINGEBEN.
execute: 
  eval: true 
highlight-style: arrow 
cache: true
toc: true
number-sections: true


categories:
- inference  # ENTER CATEGORIES HERE
- frequentist


bibliography: "../../library-ses.bib"

knitr:
  opts_chunk:
    out.width: "75%"

---





# Aufgabe 

Welche Aussage zum p-Wert ist korrekt?


A) Der p-Wert ist die Wahrscheinlichkeit, dass die Nullhypothese wahr ist.
B) Der p-Wert gibt die Wahrscheinlichkeit an, dass die Alternativhypothese falsch ist.
C) Ein p-Wert von 0,05 bedeutet, dass es eine 5%ige Chance gibt, dass das Ergebnis zufällig entstanden ist."
D) Ein kleinerer p-Wert bedeutet einen stärkeren Effekt.
E) "p = 0,049 ist 'signifikant', aber p = 0,051 ist 'nicht signifikant' - das sind kategorisch verschiedene Ergebnisse."
Hinweise:
F) Ein nicht-signifikanter p-Wert beweist, dass kein Effekt existiert.
G) Der p-Wert gibt an, wie wahrscheinlich es ist, dass man das gleiche Ergebnis bei Wiederholung erhält.
H) p < 0,001 bedeutet, dass das Ergebnis praktisch relevant ist.



- Beachten Sie die üblichen [Hinweise](https://datenwerk.netlify.app/hinweise) des Datenwerks.


</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>











# Lösung 


A) FALSCH. Der p-Wert ist P(Daten|H₀), nicht P(H₀|Daten)
B) FALSCH. Der p-Wert macht keine Aussage über die Wahrscheinlichkeit von Hypothesen.
C) FALSCH. Der p-Wert macht keine Aussage über die Ursachen eines Befunds.
D) FALSCH. Der p-Wert und die Effektgröße sind verschiedene Konzepte. Ein kleiner p-Wert bedeutet nicht (notwendig) einen großen Effekt.
E) FALSCH. Arbiträre Schwellenwerte schaffen keine qualitativen Unterschiede. Der Unterschied zwischen signifikant und nicht-signifikant ist nicht signifikant (Andrew Gelman).
F) Falsch! Fehlende Evidenz ≠ Evidenz für Fehlen.
G) Falsch! Das wäre die Reproduzierbarkeit, nicht der p-Wert.
H) Falsch! Statistische und praktische Signifikanz sind verschiedene Konzepte.

