---
extype: num
exsolution: r sol
exname: wertberechnen
expoints: 1
extol: 0.1
categories:
- R
- dyn
- num
date: '2023-03-23'
slug: Wertberechnen
title: Wertberechnen

---



```{r libs, include = FALSE}

# library(tidyverse)
# library(mosaic)

```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```










# Aufgabe

```{r echo = FALSE}
x <- sample(c(0, 3, 8, 15, 24), size = 1)
```

Welchen Wert bzw. welches Ergebnis liefert folgende R-Syntax für `ergebnis` zurück?

`x` hat zu Beginn den Wert `r x`. 

*Hinweis*: `sqrt(x)` liefert die (positive) Quadratwurzel von `x` zurück.





```{r}
y <- 0

x <- x + y

y = x

x <- x + 1

ergebnis <- sqrt(x)
```



</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung



```{r echo = FALSE}
sol <- ergebnis
```

Es wird `r sol` zurückgeliefert.




---

Categories: 

- R
- dyn
- num

