---
# gleich diese Datei in einem Ordner mit Namen der Aufgabe abspeichern!
date: 2024-10-15
draft: FALSE   # ACHTUNG DRAFT STEHT AUF TRUE!
title: remove-digits  # HIER TITEL DES POSTS EINGEBEN.
execute: 
  
  eval: true 
highlight-style: arrow 
cache: true
toc: true
number-sections: true
extype: string
exsolution: ""
exshuffle: no
categories:
- textmining  # ENTER CATEGORIES HERE
- string

bibliography: "../../library-ses.bib"


---





# Aufgabe 



# Aufgabe

Schreiben Sie einen R-Code,
der aus dem folgenden String-Vektor,
die Anzahl der uniquen Werte ausgibt,
*nachdem* alle Zahlen aus dem Vektor entfernt wurden.

Hier ist der String-Vektor:

```{r}
col_names <- 
  c("key01",
    "key02",
    "value01",
    "value02")
```


die Lösung sollte also sein: "key, value".




</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>













# Lösung


Setup:

```{r}
library(tidyverse)
```




Zahlen entfernen:


```{r}
col_names_unique <- 
  col_names %>% 
  str_remove_all("[:digit:]") |>  # aus "stringr"
  unique()

col_names_unique
```

Alternativen, um Zahlen zu entfernen:

```{r}
col_names %>% 
  str_remove_all("[0-9]") 
```

Weitere Alternative:


```{r}
col_names |> 
  str_remove_all("\\d+$") 
```


Alternative mit base-R:

```{r}
gsub("[0-9]+$","", col_names) 

```



