---
exname: rope-regression
extype: num
exsolution: r sol
exshuffle: no
extol: 1
expoints: 1
categories:
- bayes
- regression
- rope
- qm2
- qm2-pruefung
date: '2022-12-15'
slug: rope-regression
title: rope-regression

---




```{r libs, include = FALSE}
library(tidyverse)
library(glue)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```






# Exercise

John Kruschke hat einen (Absolut-)Wert vorschlagen, als Grenze für Regressionskoeffizienten "vernachlässigbarer" Größe.

Nennen Sie diesen Wert!

Hinweise:

- Geben Sie nur Zahlen ein (und ggf. Dezimaltrennzeichen).
- Führende Nullen  dürfen auch bei Zahlen kleiner als 1 nicht weggelassen werden.




</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Solution

```{r}
sol <- 0.05
```

`r sol`




---

Categories: 

- bayes
- regression
- rope

