---
# gleich diese Datei in einem Ordner mit Namen der Aufgabe abspeichern!
date: 2025-06-27
draft: FALSE   # ACHTUNG DRAFT STEHT AUF TRUE!
title: penguins-postbreite  # HIER TITEL DES POSTS EINGEBEN.
execute: 
  eval: true 
highlight-style: arrow 
cache: true
toc: true
number-sections: true


categories:
- bayes  # ENTER CATEGORIES HERE
- regression

bibliography: "../../library-ses.bib"

knitr:
  opts_chunk:
    out.width: "75%"

---





# Aufgabe 

 Eine Forscherin untersucht folgende Forschungsfrage:
Gibt es einen substanziellen Zusammenhang von
Flossenlänge (mm, Flipper, UV) und Gewicht (g, AV) bei
Pinguinen?
Sie verwendet den Datensatz "Palmerpenguins".
Ihre Bayes-Analyse findet folgendes 95%-ETI für den Effekt
der UV: 47 Gramm bis 53 Gramm.
Auf Basis ihres biologischen Fachwissens schätzt sie
Gewichtsunterschiede (im Mittelwert) von max. 100 Gramm
als "vernachlässigbar" (nicht substanziell) ein.
Auf Basis dieser Ergebnisse: Wie soll die Forscherin ihre
Forschungsfrage beantworten?



A) Der Zusammenhang ist substanziell.
B) Der Zusammenhang ist vernachlässigbar.
C) Es ist ohne weitere Annahmen bzw. Angaben keine
Aussage möglich.
D) Die Befundlage ist unklar.


Hinweise:


- Beachten Sie die üblichen [Hinweise](https://datenwerk.netlify.app/hinweise) des Datenwerks.


</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>











# Lösung 


**B**


