---
exname: Ridges-vergleichen
extype: schoice
exsolution: 64
exshuffle: 5
expoints: 1
categories:
- vis
- dyn
- schoice
date: '2023-02-26'
slug: Ridges-vergleichen
title: Ridges-vergleichen

---





```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      dpi = 96,
                      message = FALSE,
                      echo = FALSE)
```













# Aufgabe



```{r ridgeplot, echo = FALSE}
library(ggridges)
library(tidyverse)
data(diamonds)


ggplot(diamonds, aes(x = price, y = cut, fill = stat(x))) +
  geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01) +
  scale_fill_viridis_c(name = "price", option = "C") 
```




Answerlist
----------

* Die Mittelwerte der Histogramme sind identisch.
* Die Mediane der Histogramme sind identisch.
* Die Histogramme sind (alle) linksschief.
* Die Histogramme sind (alle) rechtsschief.
* Die Färbung (Füllfarbe) kodiert die Schliffart (`cut`).
* Einige Histogramme sind normalverteilt.




</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung

Answerlist
----------
* Falsch
* Falsch
* Falsch
* Richtig
* Falsch
* Falsch




---

Categories: 

- vis
- dyn
- schoice

