---
exname: summarise01
extype: num
exsolution: 326.51
exshuffle: no
extol: 1
expoints: 1
categories:
- datawrangling
- eda
- tidyverse
- dplyr
- num
date: '2023-03-27'
slug: summarise01
title: summarise01

---






```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      cache = TRUE,
                      echo = TRUE,
                      echo = TRUE,
                      message = FALSE,
                      fig.show = "hold")

library(tidyverse)
library(exams)
```






# Aufgabe

Im Datensatz `mariokart`: 

Fassen Sie die Spalte `total_pr` zusammen und zwar zum `max`imalwert!

Geben Sie diese Zahl als Antwort zurück!   



</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung

Pakete starten:

```{r}
library(easystats)
library(tidyverse)  # startet das Paket tidyverse
```






Daten importieren:

```{r}
mariokart <- data_read("https://vincentarelbundock.github.io/Rdatasets/csv/openintro/mariokart.csv")
```




Zusammenfassen:

```{r}
mariokart_klein <- summarise(mariokart, max_preis = max(total_pr)) 
mariokart_klein
```

`min` analog.

Die Lösung lautet: 327 Euro



---

Categories: 

- datawrangling
- eda
- tidyverse
- dplyr
- num

