---
extype: string
exsolution: NA
exname: Inferenz-fuer-alle
expoints: 1
categories:
- qm2
- inference
- uncertainty
date: '2022-09-04'
slug: Inferenz-fuer-alle
title: Inferenz-fuer-alle

---




```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      cache = TRUE)
```









# Exercise

Die Inferenzstatistik ist eine Sammlung an Verfahren zur Bemessung von Unsicherheit in statistischen Schlüssen.

a) Für welche Statistiken - also Kennzahlen der Deskriptivstatistik wie etwa $\bar{X}, sd, r$ - kann man die Inferenzstatistik verwenden?

b) Für welche Forschungsfragen oder -bereiche kann man die Inferenzstatistik verwenden?

c) Gibt es besondere Fälle, in denen man nicht die Inferenzstatistik verwenden möchte? Wenn ja, welche?



</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Solution

a) Für (grundsätzlich) alle: Für jede Statistik kann man prinzipiell von der jeweiligen Stichprobe (auf Basis derer die Statistik berechnet wurde) auf eine zugehörige Grundgesamtheit schließen.

b) Für (grundsätzlich) alle: Die Methoden der Inferenzstatistik sind prinzipiell unabhängig von den Spezifika bestimmter Forschungsfragen oder -bereiche. In den meisten Forschungsfragen ist man daran interessiert *allgemeingültige* Aussagen zu treffen. Da Statistiken sich nur auf eine Stichprobe - also einen zumeist nur kleinen Teil einer Grundgesamtheit beziehen - wird man sich kaum mit einer Statistik zufrieden geben, sondern nach Inferenzstatistik verlangen. 

c) In einigen Ausnahmefällen wird man auf eine Inferenzstatistik verzichten. Etwa wenn man bereits eine Vollerhebung durchgeführt hat, z.B. alle Mitarbeitis eines Unternehmens befragt hat, dann kennt man ja bereits den wahren Populationswert. Ein anderer Fall ist, wenn man nicht an Verallgemeinerungen interessiert ist: Kennt man etwa die Überlebenschance $p$ des Titanic-Unglücks, so ist es fraglich auf welche Grundgesamtheit man die Statistik $p$ bzw. zu welchem Paramter $\pi$ (kleines Pi) man generalisieren möchte.




---

Categories: 

- qm2
- inference
- uncertainty

