---
exname: poaerior_interval
extype: schoice
exsolution: 8
exshuffle: no
categories:
- bayes
- regression
- post
date: '2022-12-15'
slug: posterior_interval
title: posterior_interval

---




```{r libs, include = FALSE}
library(tidyverse)

```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```






# Exercise

Welches Ergebnis hat der R-Befehl `posterior_interval()` (R-Paket `rstanarm`)?

Wählen Sie die (am besten) passende Antwort aus.

Hinweis:

- Soweit nicht anders benannt, ist immer die Voreinstellung der betreffenden Funktion gemeint.

Answerlist
----------
* Er liefert einen Vorhersagewert aus der Posteriori-Verteilung.
* Er liefert ein Vorhersageintervall aus der Posteriori-Verteilung.
* Er liefert ein 90%-Vorhersageintervall aus der Posteriori-Verteilung.
* Er liefert ein 95%-Vorhersageintervall aus der Posteriori-Verteilung.
* Er liefert ein HDI-Vorhersageinterval aus der Posteriori-Verteilung.




</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Solution

So können Sie sich Hilfe zu diesem Befehl ausgeben lassen:

```{r echo = TRUE, eval = FALSE}
help(posterior_interval)
```



Answerlist
----------


* Falsch
* Falsch
* Wahr
* Falsch
* Falsch





---

Categories: 

- bayes
- regression
- post

