---
# gleich diese Datei in einem Ordner mit Namen der Aufgabe abspeichern!
date: 2024-07-02
draft: false   # ACHTUNG DRAFT STEHT AUF TRUE!
title: pd1  # HIER TITEL DES POSTS EINGEBEN.
execute: 
  eval: true 
highlight-style: arrow 
cache: true
toc: true
number-sections: true


categories:
- inference  # ENTER CATEGORIES HERE
- bayes

bibliography: "../../library-ses.bib"

knitr:
  opts_chunk:
    out.width: "75%"

---





# Aufgabe 


Was beschreibt der Koeffizient "Probability of Direction" (pd) in der Bayes'schen Statistik?


A) Die Wahrscheinlichkeit, dass ein Parameter einen bestimmten numerischen Wert annimmt, basierend auf der Prior-Verteilung.
B) Den Anteil der Posteriori-Verteilung, der das gleiche Vorzeichen hat wie der Median; und gibt damit die Wahrscheinlichkeit an, dass der Parameter streng positiv bzw. negativ ist.
C) Die Wahrscheinlichkeit, dass die Nullhypothese wahr ist, ausgedrückt als Prozentsatz zwischen 0 und 100%.
D) Den Korrelationskoeffizienten zwischen Prior- und Posteriori-Verteilung, der angibt, wie stark die Daten die Vorannahmen beeinflussen.
E) Die Wahrscheinlichkeit, dass ein Parameter innerhalb des 95%-Kredibilitätsintervalls liegt, unabhängig von seinem Vorzeichen.
F) Die standardisierte Abweichung des Parameters vom Nullwert, normiert auf eine Skala von 50% bis 100%.


Hinweise:


- Beachten Sie die üblichen [Hinweise](https://datenwerk.netlify.app/hinweise) des Datenwerks.


</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>











# Lösung 


 **B**
 
Die *pd* gibt an, mit welcher Wahrscheinlichkeit ein Parameter das gleiche Vorzeichen hat wie sein Median und variiert zwischen 50% (maximale Unsicherheit über die Richtung) und 100% (vollständige Gewissheit über die Richtung des Effekts).

