---
exname: wrangle9
extype: num
exsolution: 12
extol: 0.1
date: '2023-02-08'
slug: wrangle9
title: wrangle9
categories: num

---




```{r libs, include = FALSE}
library(tidyverse)
library(testthat)
library(glue)
library(printr)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```






# Aufgabe

Um Variablen in einem Datensatz anzulegen oder zu verändern, nutzt man `mutate()` im tidyverse. `mutate()` ist nützlich für vektorielles Rechnen. In diesem Zusammenhang: Was ist das Ergebnis folgenden Ausdrucks?


```{r echo = TRUE, eval = FALSE}
sum(1:3 + 1:3)
```






</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung


12



```{r echo = TRUE, eval = TRUE}
sum(1:3 + 1:3)
```





---

Categories: 

num

