---
exname: sd-vergleich
extype: schoice
exsolution: 64
exshuffle: no
categories:
- datawrangling
- eda
- tidyverse
- vis
- variability
- schoice
date: '2023-04-28'
slug: sd-vergleich
title: sd-vergleich

---




```{r libs, include = FALSE}
library(tidyverse)
library(mosaic)
library(viridis)
library(gridExtra)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 7,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```






# Aufgabe


Welches der folgenden Diagramm hat die größte Streuung, 
gemessen in Standardabweichung (sd, sigma)?





```{r echo = FALSE, warning=FALSE, message=FALSE}

# Code by Karsten Lübke


library(gridExtra)
library(viridis)
library(mosaic)

xs1 <- rnorm(1000)
xs2 <- rnorm(1000, sd = 2)
xs3 <- runif(1000, -6, 6)

hs1 <- gf_histogram( ~ xs1,
                     xlab = NULL,
                     title = "A",
                     fill = viridis(1, alpha = 0.6),
                     color = "darkgrey") %>%
  gf_lims(x=c(-6,6))

hs2 <- gf_histogram( ~ xs2,
                     xlab = NULL,
                     title = "B",
                     fill = viridis(1, alpha = 0.6),
                     color = "darkgrey") %>%
  gf_lims(x=c(-6,6))

hs3 <- gf_histogram( ~ xs3,
                     xlab = NULL,
                     title = "C",
                     fill = viridis(1, alpha = 0.6),
                     color = "darkgrey") %>%
  gf_lims(x=c(-6,6))

grid.arrange(hs1, hs2, hs3, nrow = 3)



```




Answerlist
----------
* A
* B
* C
* alle gleich
* keine Antwort möglich



</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung

Die SD ist am größten in Diagramm C

Answerlist
----------


* Falsch. Dieses Diagramm hat die kleinste Streuung
* Falsch.
* Wahr.
* Falsch. Die Streuungen sind unterschiedlich.
* Falsch.





---

Categories: 

- datawrangling
- eda
- tidyverse
- vis
- variability
- schoice

