{
  "hash": "e0b0331f91983eeb716f2e464341ee34",
  "result": {
    "engine": "knitr",
    "markdown": "---\nexname: bed-post-wskt1\nextype: schoice\nexsolution: 64\nexshuffle: no\ncategories:\n- regression\n- bayes\n- post\ndate: '2022-12-09'\ntitle: Bed-Post-Wskt1\n\n---\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n\n\n\n# Exercise\n\nBeziehen Sie sich auf das Regressionsmodell, für das die Ausgabe mit `stan_glm()` hier dargestellt ist:\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Parameter   |      Median|   CI|      CI_low|    CI_high| pd|      Rhat|      ESS|Prior_Distribution | Prior_Location| Prior_Scale|\n|:-----------|-----------:|----:|-----------:|----------:|--:|---------:|--------:|:------------------|--------------:|-----------:|\n|(Intercept) | 146.1050983| 0.95| 145.1605321| 147.075639|  1| 0.9997636| 4475.401|normal             |       154.5971|   19.355830|\n|weight_c    |   0.9034848| 0.95|   0.8201613|   0.984254|  1| 0.9998113| 4535.592|normal             |         0.0000|    2.997786|\n\n</div>\n:::\n:::\n\n\n\n\n\n\n\nBetrachten Sie folgende Beziehung (Gleichung bzw. Ungleichung):\n\n$$Pr(\\text{height}_i = 155|\\text{weightcentered}_i=10, \\alpha, \\beta, \\sigma) \\quad \\Box \\quad Pr(\\text{height}_i = 160|\\text{weightcentered}_i=10, \\alpha, \\beta, \\sigma)$$\nDie in der obigen Beziehung angegebenen Parameter beziehen sich auf das oben dargestellt Modell.\n\nErgänzen Sie das korrekte Zeichen in das Rechteck $\\Box$!\n\nAnswerlist\n----------\n* $\\lt$\n* $\\le$\n* $\\gt$\n* $\\ge$\n* $=$\n\n\n\n\n</br>\n</br>\n</br>\n</br>\n</br>\n</br>\n</br>\n</br>\n</br>\n</br>\n\n# Solution\n\n\nAls Prädiktorwert (X-Variable) wurde der Achsenabschnitt spezifiziert, also $x=10$. \nDer Achsenabschnitt wird mit 146.11 angegeben. \nJe weiter ein $y_i$ vom vorhergesagten Wert, $\\hat{y}$ entfernt ist, desto unwahrscheinlicher ist es,\ngegeben dem Prädiktorwert und dem Modell und den Daten.\nFür jede Einheit von $X$ wird $Y$ größer, also weiter weg von Null.\n\nDer vorhergesagte Wert $\\hat{y}$ lässt sich aus der Tabelle mit den Parameterwerten berechnen:\n\n$\\hat{y} = \\beta_0 + x \\cdot \\beta_1$ \n\n\nFür das vorliegende Beispiel heißt das:\n\n\n$\\hat{y} = 146.11 + 10 \\cdot 0.9$.\n\nDas Ergebnis ist:\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept) \n     155.11 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\nIm Detail:\n\nPakete starten:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rstanarm)\nlibrary(tidyverse)\nlibrary(easystats)\n```\n:::\n\n\n\n\n\n\nDaten importieren:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nKung_path <-  \n  \"https://raw.githubusercontent.com/sebastiansauer/Lehre/main/data/Howell1a.csv\"  \n\nd <- read.csv(Kung_path) \n```\n:::\n\n\n\n\n\n\nDaten zentrieren:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd <-\n  d |> mutate(weight_c = weight - mean(weight))\n```\n:::\n\n\n\n\n\nNur Erwachsene:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd <-\n  d |> \n  filter(age >= 18)\n```\n:::\n\n\n\n\n\n\nModell berechnen:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod <- stan_glm(height ~ weight_c, data = d, refresh = 0)\n```\n:::\n\n\n\n\n\n\nParamter des Modells:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nparameters(mod)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Parameter   |      Median|   CI|      CI_low|    CI_high| pd|      Rhat|      ESS|Prior_Distribution | Prior_Location| Prior_Scale|\n|:-----------|-----------:|----:|-----------:|----------:|--:|---------:|--------:|:------------------|--------------:|-----------:|\n|(Intercept) | 146.1050983| 0.95| 145.1605321| 147.075639|  1| 0.9997636| 4475.401|normal             |       154.5971|   19.355830|\n|weight_c    |   0.9034848| 0.95|   0.8201613|   0.984254|  1| 0.9998113| 4535.592|normal             |         0.0000|    2.997786|\n\n</div>\n:::\n:::\n\n\n\n\n\n\nModell visualisieren:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimate_relation(mod) |> plot()\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](Bed-Post-Wskt1_files/figure-html/unnamed-chunk-11-1.png){width=100%}\n:::\n:::\n\n\n\n\n\n\n\n\nWie man im Diagramm sieht, ist die Wahrscheinlichkeit bei `x = 10` für `y=155` größer als für `y=160`.\n\nDie Wahrscheinlichkeit für einen bestimmten Y-Wert gegeben x = 10` ist auf der Regressionsgeraden am größten (blauer Punkt).\nDie Punkte auf der Regressionsgeraden sind die vorhergesagten Y-Wert ($\\hat{y}$) für die gegebenen X-Werte.\n\nAnswerlist\n----------\n\n\n* Falsch\n* Falsch\n* Wahr\n* Falsch\n* Falsch\n\n\n\n\n\n---\n\nCategories: \n\n- regression\n- bayes\n- post\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}