---
exname: there-is-no-package
extype: schoice
exsolution: 512
exshuffle: no
categories:
- R
- '2023'
- schoice
date: '2023-03-23'
slug: there-is-no-package
title: there-is-no-package

---




```{r libs, include = FALSE}
library(tidyverse)
library(testthat)
library(glue)
library(printr)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```






# Aufgabe



Sie führen folgende R-Syntax aus:

```
library(tidyverse)
````


Und bekommen als Antwort eine Fehlermeldung quittiert:

`there is no package called 'tidyverse'`.


Was ist die Ursache bzw. zu tun?






Answerlist
----------
* Es existiert kein Paket namens `tidyverse`.
* Es existiert kein Paket namens `tidyverse` auf Ihrem Rechner.
* Das Paket `tidyverse` ist nicht gestartet.
* Das Paket `tidyverse` ist kaputt.
* R ist in Sie verliebt und versucht auf ungelenke Weise Kontakt aufzunehmen.




</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung

Es existiert kein Paket namens `tidyverse` auf Ihrem Rechner; vgl [hier](https://r4ds.had.co.nz/data-visualisation.html#prerequisites-1).


Answerlist
----------


* Falsch
* Wahr
* Falsch
* Falsch
* Falsch





---

Categories: 

- R
- '2023'
- schoice

