---
exname: Verteilungen-Quiz-16
extype: schoice
exsolution: 10
exshuffle: no
categories:
- distributions
- Verteilungen-Quiz
- probability
- bayes
- simulation
date: '2022-11-20'
slug: Verteilungen-Quiz-16
title: Verteilungen-Quiz-16

---





```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = TRUE,
                      message = FALSE,
                      fig.show = "hold")



```






# Exercise



Für die Körpergröße des deutschen Mannes $X$ gelte $X \sim N(180,06)$ (in Zentimetern).


[Quelle Mittelwert](https://de.wikipedia.org/wiki/Liste_der_L%C3%A4nder_nach_K%C3%B6rpergr%C3%B6%C3%9Fe)
[Quelle SD geschätzt](https://en.wikipedia.org/wiki/Average_human_height_by_country)

Ähnliche Daten finden sich bei [Our World in Data](https://ourworldindata.org/human-height#height-is-normally-distributed).

Ist folgende Aussage wahr?

Das 50%-Quantil von $X$ beträgt 180.

Answerlist
----------

* Ja
* Nein



</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Solution

```{r}
qnorm(p = .5, mean = 180, sd = 6)
```



Answerlist
----------







* Wahr
* Falsch



---

Categories: 

- distributions
- Verteilungen-Quiz
- probability
- bayes
- simulation

