---
exname: wozu-streudiagramm
extype: schoice
exsolution: 1
exshuffle: no
categories:
- vis
- '2023'
- schoice
date: '2023-02-26'
slug: wozu-streudiagramm
title: wozu-streudiagramm

---




```{r libs, include = FALSE}
library(tidyverse)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = TRUE,
                      message = FALSE,
                      fig.show = "hold")

```






# Aufgabe

Zu welchem Zweck ist ein *Streudiagramm* am besten geeignet?



Answerlist
----------
* Um Verteilungen einer nominalen Variablen darzustellen.
* Um Verteilungen einer metrischen Variablen darzustellen.
* Um Verteilungen einer stetigen, metrischen Variablen darzustellen.
* Um Zusammenhänge zwischen zwei nominalen Variablen darzustellen.
* Um Zusammenhänge zwischen zwei metrischen Variablen darzustellen.






</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung

Um Zusammenhänge zwischen zwei metrischen Variablen darzustellen.



Answerlist
----------


* Falsch
* Falsch
* Falsch
* Falsch
* Wahr




---

Categories: 

- vis
- '2023'
- schoice

