---
exname: zwert1
extype: num
exsolution: r x1_z
exshuffle: no
extol: 0.3
expoints: 1
categories:
- z-value
- R
- math
date: '2022-12-14'
slug: zwert-berechnen
title: zwert-berechnen

---




```{r libs, include = FALSE}
library(tidyverse)
library(glue)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```






# Exercise

```{r}
x1 = 28
x_mw = 42
x_sd = 7
```


Sei $X \sim \mathcal{N}(`r x_mw`, `r x_sd`)$ und $x_1 = `r x1`$.

Berechnen Sie den z-Wert für $x_1$!

Hinweis:

- Runden Sie ggf. auf die nächste ganze Zahl.



</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Solution

```{r echo = TRUE}
x1_z = (x1 - x_mw) / x_sd
```


`r x1_z`





---

Categories: 

- z-value
- R
- math

