---
# gleich diese Datei in einem Ordner mit Namen der Aufgabe abspeichern!
date: 2025-12-17  # DATUM AKTUALISIEREN!
draft: false   # ACHTUNG DRAFT STEHT AUF TRUE!
title:  zuordnung_regr_formel1  # HIER TITEL DES POSTS EINGEBEN.
execute: 
  eval: true 
  cache: true
highlight-style: arrow 
toc: true
number-sections: true


categories:
- regression  # ENTER CATEGORIES HERE

---





# Aufgabe 

Weltweit gibt es in immer mehr Städten Fahrradverleih-Dienste.
Aus betriebswirtschaftlicher Sicht stellt sich die Frage, welche Variablen die Nutzung eines Leihrades vorhersagen?
Eine datenanalytische Grundlage bietet das [Bike Sharing Data set](https://archive.ics.uci.edu/dataset/275/bike+sharing+dataset), z.B. von der [UV Irvine](https://archive.ics.uci.edu/).

Hier ist das Codebook zum Datensatz:


----

- instant: record index
- dteday : date
- season : season (1:springer, 2:summer, 3:fall, 4:winter)
- yr : year (0: 2011, 1:2012)
- mnth : month ( 1 to 12)
- holiday : weather day is holiday or not (extracted from http://dchr.dc.gov/page/holiday-schedule)
- weekday : day of the week
- workingday : if day is neither weekend nor holiday is 1, otherwise is 0.
- weathersit :
  - 1: Clear, Few clouds, Partly cloudy, Partly cloudy
  - 2: Mist + Cloudy, Mist + Broken clouds, Mist + Few clouds, Mist
  - 3: Light Snow, Light Rain + Thunderstorm + Scattered clouds, Light Rain + Scattered clouds
  - 4: Heavy Rain + Ice Pallets + Thunderstorm + Mist, Snow + Fog
- temp : Normalized temperature in Celsius. The values are divided to 41 (max)
- atemp: Normalized feeling temperature in Celsius. The values are divided to 50 (max)
- hum: Normalized humidity. The values are divided to 100 (max)
- windspeed: Normalized wind speed. The values are divided to 67 (max)
- casual: count of casual users
- registered: count of registered users
- cnt: count of total rental bikes including both casual and registered

---

**Aufgabe:**
Ordnen Sie die richtige Forschungsfrage der Regressionsformel zu.


Regressionsformel:
`cnt ~ workingday`


Forschungfragen:


A) Ist die Anzahl der aktuell gemieteten Fahrrädern hoch?
B) Ist die Anzahl der aktuell gemieteten Fahrrädern abhängig vom Wochentag?
C) Wie hoch ist die Anzahl der aktuell gemieteten Fahrrädern?
D) Kann man den Wochentag vorhersagen anhand der Anzahl der aktuell gemieteten Fahrrädern?
E) Hat der Wochentag einen kausalen Einfluss auf die Anzahl der aktuell gemieteten Fahrrädern?

Hinweise:


- Beachten Sie die üblichen [Hinweise](https://datenwerk.netlify.app/hinweise) des Datenwerks.


</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>











# Lösung 


B) Ist die Anzahl der aktuell gemieteten Fahrrädern abhängig vom Wochentag?



