---
# gleich diese Datei in einem Ordner mit Namen der Aufgabe abspeichern!
date: 2024-12-13
draft: FALSE   # ACHTUNG DRAFT STEHT AUF TRUE!
title: qm2-quiz-globus # HIER TITEL DES POSTS EINGEBEN.
execute: 
  
  eval: true 
highlight-style: arrow 
cache: true
toc: true
number-sections: true
extype: string
exsolution: ""
exshuffle: no
categories:
- qm2  # ENTER CATEGORIES HERE
- 2024
- bayes

bibliography: "../../library-ses.bib"

knitr:
  opts_chunk:
    out.width: "75%"

---





# Aufgabe 


**Geben Sie jeweils an, ob die Aussage richtig oder falsch ist.**





1. Der Prozess des Bayes-Updates hat folgende drei Teile: Priori-Verteilung -> Likelihood -> Posteriori-Verteilung. 
2. Die Likelihood-Funktion ist die Wahrscheinlichkeit, der Daten unter der Annahme einer bestimmten Hypothese bzw. bestimmter Parameterwerte. 
3. Die Likelihood kann nie Null sein. 
4. Die Posteriori-Wahrscheinlichkeit (einer bestimmten Hypothese) kann nie Null sein. 
5. Die Priori-Wahrscheinlichkeit (einer bestimmten Hypothese) kann nie Null sein. 
6. Die Posteriori-Wahrscheinlichkeit misst die Wahrscheinlichkeit einer Hypothese, gegeben der Daten und der Priori-Verteilung und des Modells. 
7. Bei einer Gleichverteilung ist jede Wert gleich wahrscheinlich. 
8. Bayes' Theorem kann man so darstellen: $Pr(H|D) = \frac{ Pr(H) \cdot Pr(D|H) }{Pr(D)}$. 
9. Das Produkt von Likelihood und Priori-Wahrscheinlichkeit nennt man Evidenz. 
10. Die *standardisierte* Posteriori-Wahrscheinlichkeit ist gleich dem Produkt von Priori-Wahrscheinlichkeit und Likelihood. 
11. Sei die Priori-Wahrscheinlichkeit $Pr(H) = .1$ und die Likelihood $Pr(D|H) = .25$. Dann ist die Posteriori-Wahrscheinlichkeit $Pr(H|D) = .25$. 
12. Die Posteriori-Verteilung (Kurz: “Post-Verteilung”, oder “Post”) zeigt, wie plausibel wir jeden Wert von  halten, nachdem wir die Daten des Versuchs kennen. 
13. $Pr(H|D)$ nennt man auch die Likelihood. 
14. Wenn ein Krebstest eine Sicherheit von 90% hat (d.h. $Pr(+|K) = .9$), dann ist die Wahrscheinlichkeit, wirklich Krebs zu haben, wenn der Test positiv ist, gleich 90%. 



</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>











# Lösung 


1. Der Prozess des Bayes-Updates hat folgende drei Teile: Priori-Verteilung -> Likelihood -> Posteriori-Verteilung. *R*
2. Die Likelihood-Funktion ist die Wahrscheinlichkeit, der Daten unter der Annahme einer bestimmten Hypothese bzw. bestimmter Parameterwerte. *R*
3. Die Likelihood kann nie Null sein. *F*
4. Die Posteriori-Wahrscheinlichkeit (einer bestimmten Hypothese) kann nie Null sein. *F*
5. Die Priori-Wahrscheinlichkeit (einer bestimmten Hypothese) kann nie Null sein. *F*
6. Die Posteriori-Wahrscheinlichkeit misst die Wahrscheinlichkeit einer Hypothese, gegeben der Daten und der Priori-Verteilung und des Modells. *R*
7. Bei einer Gleichverteilung ist jede Wert gleich wahrscheinlich. *R*
8. Bayes' Theorem kann man so darstellen: $Pr(H|D) = \frac{ Pr(H) \cdot Pr(D|H) }{Pr(D)}$. *R*
9. Das Produkt von Likelihood und Priori-Wahrscheinlichkeit nennt man Evidenz. *F*
10. Die *standardisierte* Posteriori-Wahrscheinlichkeit ist gleich dem Produkt von Priori-Wahrscheinlichkeit und Likelihood. *F*
11. Sei die Priori-Wahrscheinlichkeit $Pr(H) = .1$ und die Likelihood $Pr(D|H) = .25$. Dann ist die Posteriori-Wahrscheinlichkeit $Pr(H|D) = .25$. *F*
12. Die Posteriori-Verteilung (Kurz: “Post-Verteilung”, oder “Post”) zeigt, wie plausibel wir jeden Wert von  halten, nachdem wir die Daten des Versuchs kennen. *R*
13. $Pr(H|D)$ nennt man auch die Likelihood. *F*
14. Wenn ein Krebstest eine Sicherheit von 90% hat (d.h. $Pr(+|K) = .9$), dann ist die Wahrscheinlichkeit, wirklich Krebs zu haben, wenn der Test positiv ist, gleich 90%. *F*


