---
exname: shrinkage1
extype: schoice
exsolution: 10000
exshuffle: no
expoints: 4
date: '2023-05-17'
slug: Shrinkage1
title: Shrinkage1
categories: schoice

---




```{r libs, include = FALSE}
library(tidyverse)
library(testthat)
library(glue)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```






# Aufgabe

*Shrinkage* (Penalisierung) ist eine Erweiterung der klassischen Linearen Modelle. Welche Aussage dazu ist richtig?


Answerlist
----------
* Die Modellkoeffizienten von penalisierten linearen Modelle können wie normale lineare Modelle interpretiert werden.
* Die L2-Norm der Penalisierung kann zur Auswahl von Prädiktoren herangezogen werden.
* Die L1-Norm der Penalisierung wird auch als *Ridge-Regression* bezeichnet.
* Die Ridge-Regression ist ein Algorithmus, der eine Größe minimiert, in der ein Strafterm zum üblichen Least-Square-Termin hinzuaddiert wird, wobei dieser Strafterm die (mit $\lambda$) gewichtete Summe der Absolutwerte der $\beta$-Koeffizienten beschreibt.
* Die Lasso-Regression liefert im Vergleich zur Ridge-Regression tendenziell bessere Ergebnisse, wenn das Kriterium eine Funktion von vielen Prädiktoren ist, deren Koeffizienten jeweils etwa gleich stark sind.



</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung


Answerlist
----------


* Wahr
* Falsch
* Falsch
* Falsch
* Falsch





---

Categories: 

schoice

