---
exname: anova-skalenniveau
extype: schoice
exsolution: 10000
exshuffle: no
categories:
- variable-levels
- anova
date: '2022-12-15'
slug: anova-skalenniveau
title: anova-skalenniveau

---




```{r libs, include = FALSE}
library(tidyverse)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```






# Exercise

Die Varianzanalyse (ANOVA) ist ein inferenzstatistisches Verfahren des Frequentismus. Welches Skalenniveau passt zu diesem Verfahren?
  
  
Answerlist
----------
* UV: nominal (mehrstufig), AV: metrisch
* UV: metrisch, AV: nominal (zweistufig)
* UV: nominal (mehrstufig), AV: nominal (mehrstufig)
* UV: metrisch, AV: nominal (zweistufig)
* UV: nominal (zweistufig), AV: metrisch





</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Solution


Answerlist
----------
  
  
* Wahr
* Falsch
* Falsch
* Falsch
* Falsch





---

Categories: 

- variable-levels
- anova

