---
exname: regex02
expoints: 1
extype: string
exsolution: NA
categories:
- textmining
- regex
- string
date: '2023-10-17'
slug: regex02
title: regex02

---



```{r global-knitr-options, include=FALSE, message=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      fig.show = "hold")
```



# Aufgabe


Matchen Sie Elemente des Vektors `txt3`, die nur aus Ziffern bestehen:


```{r}
txt3 <- c("abc", "a123", "123", "1", "1a23", "12aaaa23")
```



Hinweise:

- Orientieren Sie sich im Übrigen an den [allgemeinen Hinweisen des Datenwerks](https://datenwerk.netlify.app/hinweise).





</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung

```{r}
library(tidyverse)
```


```{r}
str_detect(txt3, "^[:digit:]+$")
```


Man kann z.B. auch `\\d` verwenden anstelle von `[:digit:]`.

Sicherlich gibt es noch mehrere weitere Lösungen.





---

Categories: 

- textmining
- regex
- string

