---
# gleich diese Datei in einem Ordner mit Namen der Aufgabe abspeichern!
date: 2024-10-28
draft: FALSE   # ACHTUNG DRAFT STEHT AUF TRUE!
title: simu-uniform  # HIER TITEL DES POSTS EINGEBEN.
execute: 
  
  eval: true 
highlight-style: arrow 
cache: true
toc: true
number-sections: true
extype: string
exsolution: ""
exshuffle: no
categories:
- probability  # ENTER CATEGORIES HERE
- simulation
- paper

bibliography: "../../library-ses.bib"


---





# Aufgabe 

Welcher der folgenden Syntax-Befehle in R ist korrekt, um eine Zufallszahl aus einer gleichverteilten Zufallsvariablen (Min: 0, Max: 10) zu generieren?


**A**

```{r}
#| eval: false
#| error: true
set.seed(42)  # Zufallszahl festlegen, nur für Reproduzierbarkeit
# "r" wie random, "unif" wie "uniform" (gleich):
runif(n = 1, min = 0, max = 10) 
```


**B**

```{r}
#| eval: false
#| error: true
set.seed(42)  # Zufallszahl festlegen, nur für Reproduzierbarkeit
# "r" wie random, "unif" wie "uniform" (gleich):
unif(n = 1, min = 0, max = 10) 
```


**C**

```{r}
#| eval: false
#| error: true
set.seed(42)  # Zufallszahl festlegen, nur für Reproduzierbarkeit
# "r" wie random, "unif" wie "uniform" (gleich):
rbinom(n = 1, min = 0, max = 11) 
```


**D**

```{r}
#| eval: false
#| error: true
set.seed(42)  # Zufallszahl festlegen, nur für Reproduzierbarkeit
# "r" wie random, "unif" wie "uniform" (gleich):
rnorm(n = 1, min = 0, max = 10) 
```



</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>











# Lösung 



**A**



