---
# gleich diese Datei in einem Ordner mit Namen der Aufgabe abspeichern!
date: 2024-11-13
draft: FALSE   # ACHTUNG DRAFT STEHT AUF TRUE!
title: small-wide-normal  # HIER TITEL DES POSTS EINGEBEN.
execute: 
  echo: false
  eval: true 
highlight-style: arrow 
cache: false
toc: true
number-sections: true
extype: string
exsolution: ""
exshuffle: no
categories:
- normal-distribution  # ENTER CATEGORIES HERE
- distributions
- posterior
- bayes
- pencil

bibliography: "../../library-ses.bib"

knitr:
  opts_chunk:
    out.width: "75%"

---


```{r}
library(ggplot2)

theme_set(theme_bw())
```




# Aufgabe 

Die folgenden Posterior-Verteilungen unterscheiden sich nicht in ihrem Modus, aber in ihrer Sicherheit zur Schätzung des Modus. Welche der folgenden Posterior-Verteilungen ist die sicherste?

**A**

```{r}
ggplot(data.frame(x = c(-4, 4)), aes(x = x)) +
  stat_function(fun = dnorm)
```


**B**

```{r}
ggplot(data.frame(x = c(-4, 4)), aes(x = x)) +
  stat_function(fun = dnorm, args = list(mean = 0, sd = 1.5))
```


**C**


```{r}
ggplot(data.frame(x = c(-4, 4)), aes(x = x)) +
  stat_function(fun = dnorm, args = list(mean = 0, sd = 0.5))
```



**D**



```{r}
ggplot(data.frame(x = c(-4, 4)), aes(x = x)) +
  stat_function(fun = dnorm, args = list(mean = 0, sd = 2.5))
```


</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>











# Lösung 


**C**




