---
extype: string
exsolution: NA
exname: warum-bayes
expoints: 1
tags:
- bayes
- why
- inference
categories:
- qm2
- bayes
- probability
date: '2022-11-05'
slug: Warum-Bayes
title: Warum-Bayes

---




<!-- DIE FRAGE IST ZU LEICHT. AUßERDEM LÄDT SIE ZUM SPICKEN BZW. COPY-PASTEN EIN. Ausserdem kann man die Frage einfach online recherchieren. EVTL. ALS MC-FRAGE UMBAUEN -->


# Exercise

Nennen Sie einen (fachlichen) Grund, warum Sie eine Bayes-Analyse machen würden (und nicht etwa ein Analyse auf Basis der frequentistischen Statistik).




</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Solution

Es existieren mehrere Gründe, einige wichtige sind:

- Bayes-Analysen erlauben es, Vorwissen in die Analyse einfließen zu lassen.
- Bayes-Analysen geben die Wahrscheinlichkeit einer Hypothese bzw. eines Parameterwerts zurück.
- Bayes-Analysen erlauben es, Modelle exakt und flexibel zu spezifizieren.
- Bayes-Analysen sind bei kleineren Stichproben genauer.


"Quantifizierung" ist keine ausreichende Begründung für die Verwendung der Bayes-Statistik, 
da auch z.B. eine Frequentistische Analyse Quantifizierung bietet.
Hingegen ist "Quantifizierung der Wahrscheinlichkeit der Forschungshypothese" ein valider Grund,
denn der Frequentismus erlaubt nicht die Wahrscheinlichkeit einer Hypothese zu quantifizieren.

"Wahrscheinlichkeitsaussagen" ist ebenfalls keine ausreichende Begründung für Bayes,
denn auch im Frequentismus gibt es Wahrscheinlichkeitsaussagen, auch wenn diese weniger stark in die Wahrscheinlichkeitstheorie geknüpft sind als die Bayes-Inferenz (vgl. Jaynes, 2003).

Es ist als Begründung nicht ausreichend, z.B. von "Erwartungen ans die Auswertung" zu sprechen,
wenn man auf die Priori-Verteilung als (valider) Vorteil der Bayes-Inferenz abzielen möchte.

Ebenso ist es nicht ausreichend, allgemein auf eine "höhere Zuverlässigkeit" o.Ä. der Bayes-Inferenz hinzuweisen. 

Das ROPE ist eine praktische, sinnvolle Methode, allerdings gibt es mittlerweile vergleichbare Verfahren im Frequentismus,
sog. [Äquivalenztests](https://lakens.github.io/statistical_inferences/equivalencetest.html).

Der Grund, warum Bayes-Analysen bei kleineren Stichproben zu genaueren Ergebnissen kommen, liegt im Priori-Wissen. 
Spezifiziert man z.B. eine Normalverteilung mit Sigma=1 und findet in den Daten einen Wert von zB. Sigma=6, also einen extremen Ausreißer,
so wird die Priori-Verteilung dafür sorgen, den Extremwert "zurechtzustutzen" auf einen Wert näher der Mittelwert der Verteilung.
Sofern dies sinnvoll/korrekt ist, wird man mit diesem Vorgehen zu genaueren Ergebnissen kommen.
Die Hoffnung ist, dass einzelne Extremwerte eher Messfehler sind.




---

Categories: 

- qm2
- bayes
- probability

