---
exname: wrangle10
extype: num
exsolution: 165
extol: 0.1
categories:
- eda
- lagemaßee
- num
date: '2023-04-19'
slug: wrangle10
title: wrangle10

---




```{r libs, include = FALSE}
library(tidyverse)
library(testthat)
library(glue)
library(printr)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```






# Aufgabe

Betrachten Sie folgende Tabelle:

```{r echo = TRUE}
df <- tibble(
  groesse = c(180, 190, 160, 170),
  geschlecht = c("m", "m", "f", "f")
)
df
```

*Hinweis*: Der Befehl `tibble` erstellt einen Tibble (Dataframe).

Was ist er *erste* Wert, den der folgende Ausdruck zurückliefert?

```{r echo = TRUE, eval = FALSE}
df_grouped <- group_by(df, geschlecht)

summarise(df_grouped, ergebnis = mean(groesse))

```






</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung

Die Werte werden alphabetisch (bzw. alphanumerisch) sortiert. "f" kommt vor "m" im Alphabet.

*Antwort*: 165

```{r echo = TRUE, eval = TRUE}
df_grouped <- group_by(df, geschlecht)

summarise(df_grouped, ergebnis = mean(groesse))

```






---

Categories: 

- eda
- lagemaßee
- num

