---
extype: string
exsolution: NA
exname: bayes-subjektiv
expoints: 1
date: '2022-11-05'
slug: subjektiv-Bayes
title: subjektiv-Bayes

---



```{r libs, include = FALSE}
library(tidyverse)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      message = FALSE,
                      warning = FALSE,
                      # out.width = "100%",
                      cache = TRUE)
```








# Exercise

Nennen Sie einen Aspekte der bayesianischen Analyse, der (in Teilen) subjektiv ist - abgesehen von der Wahl der Priori-Verteilung.



</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Solution

- Linearitätsannahme in (linearen) Modellen
- Wahl des Likelihoods
- Wahl der Daten
- Methoden der Modellprüfung
- Generalisierung des Modells auf andere Situationen
- Wahl der Prädiktoren







---

Categories: 

~

