---
exname: def-statistik01
extype: schoice
exsolution: 1
exshuffle: no
date: '2023-02-01'
slug: Def-Statistik01
title: Def-Statistik01
categories: schoice

---




```{r libs, include = FALSE}
library(tidyverse)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = TRUE,
                      message = FALSE,
                      fig.show = "hold")

```






# Aufgabe

Welche Definition von Statistik passt am besten?


Answerlist
----------
* Statistik fasst Daten zusammen.
* Statistik vervielfacht Daten.
* Statistik fasst Daten zusammen, um wesentliche Informationen den Daten zu entnehmen .
* Statistik fasst Daten zusammen, um wesentliche Informationen den Daten zu entnehmen und beschreibt die Ungewissheit unserer Schlüsse.





</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung

S. Skript

Answerlist
----------


* Falsch
* Falsch
* Falsch
* Wahr






---

Categories: 

- schoice

