---
exname: boxplot-aussagen
extype: schoice
exsolution: '100000000011'
exshuffle: 5
expoints: 1
categories:
- vis
- eda
- dyn
- schoice
date: '2023-02-26'
slug: Boxplot-Aussagen
title: Boxplot-Aussagen

---



```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      dpi = 96,
                      message = FALSE,
                      echo = FALSE)
```











# Aufgabe


*Hinweis: `Female` steht für Frauen; `Male` für Männer.*

Diese Aufgabe bezieht sich auf den Datensatz `tips` (aus dem R-Paket `reshape2`), den Sie ggf. [hier](https://vincentarelbundock.github.io/Rdatasets/csv/reshape2/tips.csv) herunterladen können.
Ein Data-Dictionary findet sich [hier](https://vincentarelbundock.github.io/Rdatasets/doc/reshape2/tips.html).


```{r p-boxplot-aussagen}

data(tips, package = "reshape2")
library(tidyverse)

ggplot(tips) +
  aes(x = sex, y = total_bill) +
  geom_boxplot() +
  theme_light()
```


Answerlist
----------
* Der IQR der Männer ist größer als der der Frauen.
* Der Boxplot ist schlecht geeignet, um die Verteilung mehrerer Gruppen prägnant und übersichtlich zu visualisieren.
* Der Mittelwert der Männer ist kleiner als der der Frauen.
* Die Streuung in den RANDbereichen der Frauen ist größer als die der Männer.
* Bei den Männern gibt es mehr Ausreißer als bei den Frauen.
* Die Streuung in den beiden äußeren Quartilen ist bei den Frauen  größer als bei den Männern.
* Die Verteilungen sind beide *nicht* schief.
* Die Verteilungen sind beide symmetrisch.
* Auf der X-Achse steht eine metrische (quantitative) Variable.
* Auf der Y-Achse steht eine nominale (qualitative) Variable.
* Auf der Y-Achse steht eine metrische (quantitative) Variable.
* Auf der X-Achse steht eine nominale (qualitative) Variable.


</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung




Answerlist
----------
* Wahr
* Falsch
* Falsch
* Falsch
* Falsch
* Falsch
* Falsch
* Falsch
* Falsch
* Falsch
* Wahr
* Wahr






---

Categories: 

- vis
- eda
- dyn
- schoice

