---
exname: Verteilungen-Quiz-07
extype: schoice
exsolution: 1
exshuffle: no
categories:
- distributions
- Verteilungen-Quiz
- probability
- bayes
- paper
- Verteilungen-Quiz24
- qm2
date: '2022-11-20'
slug: Verteilungen-Quiz-07
title: Verteilungen-Quiz-07

---





```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = TRUE,
                      message = FALSE,
                      fig.show = "hold")



```






# Exercise

Ist folgende Aussage $A$ wahr?

Sei $X \sim N(100,15)$, dann ist $Pr(X \le 100) \ne 1/2$.


Answerlist
----------
* Ja
* Nein



</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Solution

Tatsächlich gilt: $Pr(X \le 100) = 1/2$

$A$ ist also falsch.

```{r echo = FALSE, fig.show = "hold"}
mosaic::xpnorm(100, 100, 15)
```




Answerlist
----------





* Falsch
* Wahr





---

Categories: 

- distributions
- Verteilungen-Quiz
- probability
- bayes
- simulation

