---
exname: wskt-quiz10
extype: schoice
exsolution: 1
exshuffle: no
categories:
- quiz
- probability
- bayes
- distribution
- quiz1-qm2-ws23
- schoice
date: '2023-11-01'
slug: wskt-quiz10
title: wskt-quiz10

---




```{r global-knitr-options, include=FALSE, message=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,  # ECHO IS FALSE!!!
                      message = FALSE,
                      fig.show = "hold")
```






# Aufgabe


Sei $X \sim U(0, 2)$. 


Behauptung: Es gilt: $f(X=1) = .5$.

Hinweise:

- Orientieren Sie sich im Übrigen an den [allgemeinen Hinweisen des Datenwerks](https://datenwerk.netlify.app/hinweise).


Answerlist
----------

* Falsch
* Wahr


</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung



```{r}
dunif(x = 1, min = 0, max = 2)
```



Answerlist
----------


* Falsch
* *Wahr*








---

Categories: 

- quiz
- probability
- bayes
- distribution
- quiz1-qm2-ws23
- schoice

