---
exname: options-print
expoints: 1
extype: string
exsolution: NA
categories:
- 2023
- R
- tidyverse
- markdown
- string
date: '2023-11-08'
slug: options-print
title: options-print

---



```{r global-knitr-options, include=FALSE, message=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.show = "hold")
```



# Aufgabe

Wie kann man in R kontrollieren, wie viele Zeilen eines Tibbles gedruckt werden (am Bildschrirm)?

Fixieren Sie die Werte auf min. 5 und max. 10.


Hinweise:

- Orientieren Sie sich im Übrigen an den [allgemeinen Hinweisen des Datenwerks](https://datenwerk.netlify.app/hinweise).





</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung




```{r}
options(paged.print = FALSE,
        pillar.print_max = 15, 
        pillar.print_min = 5)
```


```{r}
mtcars
```


```{r message=FALSE}
library(tidyverse)
```


```{r}
mtcars <- as_tibble(mtcars)
mtcars
```





---

Categories: 

- 2023
- R
- tidyverse
- markdown
- string

