---
exname: na-per-col
expoints: 1
extype: string
exsolution: NA
categories:
- R
- datawrangling 
- na
- string
date: '2023-11-15'
slug: na-per-col
title: na-per-col

---



```{r global-knitr-options, include=FALSE, message=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = TRUE,  # ECHO IS FALSE PER DEFAULT!
                      message = FALSE,
                      warning = FALSE,
                      fig.show = "hold")
```



# Aufgabe

Zählen Sie die Anzahl der fehlenden Werte pro Spalte im Datensatz `penguins`.

Zeigen Sie einen prägnanten Weg.

Hinweise:

- Orientieren Sie sich im Übrigen an den [allgemeinen Hinweisen des Datenwerks](https://datenwerk.netlify.app/hinweise).


```{r}
data("penguins", package = "palmerpenguins")
```





</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung


## Weg 1

```{r}
penguins |> 
  purrr::map_int(~ sum(is.na(.)))
```


## Weg 2

```{r}
colSums(is.na(penguins))
```






---

Categories: 

- R
- wrangling
- na
- string

