---
exname: lik1
extype: schoice
exsolution: 10000
exshuffle: no
categories:
- regression
- bayes
- likelihood
date: '2022-12-09'
title: Likelihood-identifizieren

---




```{r libs, include = FALSE}
library(tidyverse)

```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```






# Exercise

Welche Zeile der folgenden Modellspezifikation zeigt den Likelihood?

$$
\begin{align}
\text{height}_i &\sim \operatorname{Normal}(\mu_i, \sigma) \\
\mu_i &= \beta_0 + \beta \cdot  \text{weight}_i\\
\alpha &\sim \operatorname{Normal}(178, 20)\\
\beta &\sim \operatorname{Normal}(5,3)\\
\sigma &\sim \operatorname{Exp}(0.1)
\end{align}
$$


**Aufgabe**: Wählen Sie die richtige Zeile aus der folgenden Liste aus.



Answerlist
----------
* 1
* 2
* 3
* 4
* 5




</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Solution


Answerlist
----------
* Richtig
* Falsch. Lineares Modell.
* Falsch. Prior Achsenabschnitt.
* Falsch. Prior Regressiongewicht.
* Falsch. Prior Streuung der AV.




---

Categories: 

- regression
- bayes
- likelihood

