---
exname: boosting1
extype: mchoice
exsolution: 11111
exshuffle: no
expoints: 4
exbuggy: 1
date: '2023-05-17'
slug: Boosting1
title: Boosting1
categories: mchoice

---


<!-- EXERCISE DOES NOT REALLY MAKE SENSE -->




```{r libs, include = FALSE}
library(tidyverse)
library(testthat)
library(glue)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```






# Aufgabe

Es handelt sich um ein *lineares* Modell, wenn man unter *linear* ein Modell folgender Form versteht:


$$f(X)=\sum_{j=1}^p f_i(X_J)$$

Wählen Sie die am besten passende Begründung, warum man unter Boosting ein lineares Modell versteht bzw. verstehen kann.


Answerlist
----------
* Boosting-Modelle bestehen aus einer Sequenz von Bäumen mit jeweils nur einer Variablen (Gabelung; *internal nodes*) und sind daher linear.
* Baumbasierte Modelle sind stets linear; Boosting ist ein baumbasiertes Modell, daher ist Boosting ein lineares Modell.
* Baumbasierte Modelle haben stets den oben skizzierten Funktionsterm $f(X)$.
* Boosting gleicht einem Random-Forest-Modell, nur dass die Bäume sequenzielle Modelle darstellen und nicht parallel (gleichzeitig) in ein Modell einfließen. Daher ist Boosting ein lineares Modell.
* Alle Boosting-Modelle erfüllen obige Funktionsgleichung und sind daher immer linear.



</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung


Answerlist
----------


* Wahr
* Wahr
* Wahr
* Wahr
* Wahr











---

Categories: 

mchoice

