---
extype: string
exsolution: NA
exname: twitter03
expoints: 1
categories:
- textmining
- twitter
date: '2022-10-24'
slug: twitter03
title: twitter03

---


---
output: html_document
editor_options: 
  chunk_output_type: console
---








# Exercise


Laden Sie die neuesten Tweets an `karl_lauterbach` herunter, die mindestens 100 Likes oder 100 Retweets haben.





</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Solution



```{r}
library(tidyverse)
library(rtweet)
```


Einloggen bei Twitter; zuerst die Credentials bereithalten:

```{r}
#| eval: false
source("/Users/sebastiansaueruser/credentials/hate-speech-analysis-v01-twitter.R")
```

Dann anmelden:

```{r}
#| eval: false
auth <- rtweet_app(bearer_token = Bearer_Token)
```



Tweets an Karl Lauterbach suchen:


```{r}
#| eval: false
karl1 <- search_tweets("@karl_lauterbach min_faves:100 OR min_retweets:100", n = 10)
```



```{r}
#| eval: false
karl1 %>% 
  select(retweet_count, favorite_count)
```



```
# A tibble: 10 × 2
   retweet_count favorite_count
           <int>          <int>
 1            56            210
 2            56            229
 3            44           1626
 4            60            225
 5            30            494
 6             5            148
 7            27            435
 8            12            178
 9            13            162
10            46            375
```


 


---

Categories: 

- textmining
- twitter

