---
date: 2023-12-18  # HEUTIGES DATUM EINTRAGEN
draft: false   # ACHTUNG DRAFT STEHT AUF TRUE!
title: saratoga-cor2  # ACHTUNG: HIER NAMEN DER AUFGABE ANGEBEN

execute: 
  eval: true 
  
highlight-style: arrow 
cache: true


extype: string
exsolution: ""
exshuffle: no
categories:
- r  # ENTER CATEGORIES HERE
- dataviz
- causal
- eda
---








```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = TRUE, 
                      message = FALSE,
                      fig.show = "hold")
```







# Aufgabe


Importieren Sie den Datensatz `saratoga`. 




Berechnen Sie dann den Zusammenhang zwischen `price` und `livingArea` pro Stufe von `bedrooms`.


Hinweise:

- Beachten Sie die [Standardhinweise des Datenwerks](https://datenwerk.netlify.app/hinweise).



</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung


## Setup

```{r}
library(tidyverse)
library(ggpubr)
```


```{r}
data("SaratogaHouses", package = "mosaicData")
```




## Gruppieren

```{r}
d2 <-
  SaratogaHouses |> 
  group_by(bedrooms)
```


## Statistiken

```{r}
d2 |> 
  summarise(korrelation = cor(livingArea, price))
```


## Visualisierung


```{r}
ggscatter(d2, 
          x = "livingArea",
          y = "price",
          facet.by = "bedrooms",
          add = "reg.line")
```

