---
exname: mariokart-sd1
extype: num
exsolution: r sol
exshuffle: no
extol: 3
expoints: 1
categories:
- datawrangling
- dplyr
- eda
- variability
- num
date: '2023-04-28'
slug: mariokart-sd1
title: mariokart-sd1

---






```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      cache = TRUE,
                      echo = TRUE,
                      message = FALSE,
                      fig.show = "hold")
```






# Aufgabe

Importieren Sie den Datensatz `mariokart` in R.
Berechnen Sie die SD des Verkaufspreis (`total_pr`) für Spiele, die neu sind *oder* (auch) über Lenkräder (`wheels`) verfügen.

Hinweise:

- Runden Sie auf 1 Dezimalstelle.



</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung

Pakete starten:

```{r message=FALSE}
library(tidyverse)
library(easystats)
```


Daten importieren:

```{r}
d_url <- "https://vincentarelbundock.github.io/Rdatasets/csv/openintro/mariokart.csv"
mariokart <- data_read(d_url)
```

```{r}
solution <-
mariokart  %>% 
  filter(cond == "new" | wheels > 0) %>% 
  summarise(pr_mean = sd(total_pr))

solution
```

```{r echo=FALSE}
sol <- exams::fmt(solution[1,1], digits = 1)
```

**Lösung:** `r sol`. 





---

Categories: 

- datawrangling
- dplyr
- eda
- variability
- num

