---
exname: wozu-balkendiagramm
extype: schoice
exsolution: 64
exshuffle: no
categories:
- vis
- '2023'
- schoice
date: '2023-02-26'
slug: wozu-balkendiagramm
title: wozu-balkendiagramm

---




```{r libs, include = FALSE}
library(tidyverse)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = TRUE,
                      message = FALSE,
                      fig.show = "hold")

```






# Aufgabe

Zu welchem Zweck ist ein *Balkendiagramm* am besten geeignet?



Answerlist
----------
* Um Mittelwerte zwischen zwei oder mehr Gruppen darzustellen.
* Um Häufigkeiten darzustellen.
* Um metrische Verteilungen darzustellen.
* Um metrische Zusammenhänge darzustellen.






</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung

Balkendiagramme eignen sich, um Häufigkeiten darzustellen. 
Zwar werden Balkendiagramme immer wieder eingesetzt, um Mittelwerte bzw. deren Unterschiede zwischen Gruppen zu visualisieren,
aber [von dieser Praxis ist abzuraten](https://github.com/cxli233/FriendsDontLetFriends#1-friends-dont-let-friends-make-bar-plots-for-means-separation).




Answerlist
----------


* Falsch
* Wahr
* Falsch
* Falsch





---

Categories: 

- vis
- '2023'
- schoice

