---
exname: streudiagramm-dino
extype: schoice
exsolution: 512
exshuffle: yes
categories:
- vis
- '2023'
- schoice
date: '2023-02-26'
slug: Streudiagramm
title: Streudiagramm

---




```{r libs, include = FALSE}
library(tidyverse)
library(testthat)
library(glue)
library(datasauRus)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```






# Aufgabe




```{r}
data(datasaurus_dozen)

datasets <- datasaurus_dozen %>% 
  distinct(dataset) %>% 
  unlist()

d_selected <- sample(datasets, 1)


d <- 
  datasaurus_dozen %>% 
  filter(dataset == d_selected)

ggplot(d, aes(x = x, y = y)) +
    geom_point() +
    theme_void() +
    theme(legend.position = "none")
```



Answerlist
----------
* -.90 
* 0
* +.90
* 1
* -1



</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung


Answerlist
----------

* Falsch
* Wahr
* Falsch
* Falsch
* Falsch





---

Categories: 

- vis
- '2023'
- schoice

