---
# gleich diese Datei in einem Ordner mit Namen der Aufgabe abspeichern!
date: 2025-09-23
draft: flase   # ACHTUNG DRAFT STEHT AUF TRUE!
title: desk-vs-wskt  # HIER TITEL DES POSTS EINGEBEN.
execute: 
  eval: true 
highlight-style: arrow 
cache: true
toc: true
number-sections: true


categories:
- probability  # ENTER CATEGORIES HERE


bibliography: "../../library-ses.bib"

knitr:
  opts_chunk:
    out.width: "75%"

---





# Aufgabe 

Vervollständigen Sie die Tabelle!


```{r}
#| echo: false
d <- tibble::tribble(
         ~Wahrscheinlichkeitstheorie,                      ~Desktiptive.Statistik,
                   "?",                                   "Merkmal",
                "?",               "relative Häufigkeit, Anteil",
       "?",   "einfache relative Häufigkeitsverteilung",
               "?", "kumulierte relative Häufigkeitsverteilung",
                    "?",                                "Mittelwert",
                           "?",                                   "Varianz"
       )
gt::gt(d)
```



Hinweise:


- Beachten Sie die üblichen [Hinweise](https://datenwerk.netlify.app/hinweise) des Datenwerks.


</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>











# Lösung 

S. Skript :-)

```{r}
#| echo: false
d <- tibble::tribble(
         ~Wahrscheinlichkeitstheorie,                      ~Desktiptive.Statistik,
                   "Zufallsvariable",                                   "Merkmal",
                "Wahrscheinlichkeit",               "relative Häufigkeit, Anteil",
       "Wahrscheinlichkeitsfunktion",   "einfache relative Häufigkeitsverteilung",
               "Verteilungsfunktion", "kumulierte relative Häufigkeitsverteilung",
                    "Erwartungswert",                                "Mittelwert",
                           "Varianz",                                   "Varianz"
       )
gt::gt(d)
```



