---
exname: durch3-durch5
expoints: 1
extype: string
exsolution: NA
categories:
- R
- challenge
- string
date: '2023-06-27'
slug: durch3-durch5
title: durch3-durch5

---




# Aufgabe

Gegeben sei ein Vektor `x`:

```{r}
x <- 1:50
```

Schreiben Sie R-Code, der "durch3" ausgibt, wenn `x` durch 3 teilbar ist und (auch) "durch5" ausgibt, wenn `x` durch5 teilbar ist.

Hinweise:

- Orientieren Sie sich im Übrigen an den [allgemeinen Hinweisen des Datenwerks](https://datenwerk.netlify.app/hinweise).





</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung


```{r}
library(tidyverse)
```


```{r}
d <-
  tibble(
    x = 1:50,
    txt = ""
  ) %>% 
  mutate(txt = case_when(
    (x %% 3) == 0 ~ str_c(txt, "_durch_3"),
    TRUE ~ txt)
  ) %>% 
  mutate(txt = case_when(
    (x %% 5) == 0 ~ str_c(txt, "_durch_5"),
    TRUE ~ txt
  ))
```

So sieht die Tabelle aus:

```{r}
d
```


So kann man sich dann den Text ausgeben lassen:

```{r}
d$txt
```

Oder so:

```{r}
d$txt %>% discard(\(x) x == "")
```





---

Categories: 

- r
- challenge
- string

