---
extype: string
exsolution: NA
exname: griech-buchstaben
expoints: 1
categories:
- qm2
- inference
- parameters
date: '2022-12-14'
slug: Griech-Buchstaben-Inferenz
title: Griech-Buchstaben-Inferenz

---









# Exercise




```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      cache = TRUE)
```




```{r libs, include = FALSE}

library(tidyverse)
library(knitr)

```


Für Statistiken (Stichprobe) verwendet man meist lateinische Buchstaben; 
für Parameter (Population) verwendet man  meist (die entsprechenden) griechischen Buchstaben.

Vervollständigen Sie folgende Tabelle entsprechend!



```{r}
tibble::tribble(
                      ~Kennwert,              ~Statistik, ~Parameter,
                   "Mittelwert",              "$\\bar{X}$",         NA,
         "Mittelwertsdifferenz", "$\\bar{X}_1-\\bar{X}_2$",         NA,
                     "Streuung",                    "sd",         NA,
                       "Anteil",                     "p",         NA,
                  "Korrelation",                     "r",         NA,
           "Regressionsgewicht",                     "b",         NA
         ) %>% 
  kable(escape = FALSE)

```


</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Solution




```{r}
tibble::tribble(
                      ~Kennwert,              ~Statistik, ~Parameter,
                   "Mittelwert",              "$$\\bar{X}$$",         "$$\\mu$$",
         "Mittelwertsdifferenz", "$$d=\\bar{X}_1-\\bar{X}_2$$",         "$$\\mu_1$$- $$\\mu_2$$",
                     "Streuung",                    "sd",         "$$\\sigma$$",
                       "Anteil",                     "p",         "$$\\pi$$",
                  "Korrelation",                     "r",         "$$\\rho$$",
           "Regressionsgewicht",                     "b",         "$$\\beta$$"
         ) %>% 
  kable(escape = FALSE)

```



---

Categories: 

- qm2
- inference
- parameters

