---
exname: diamonds-histogram
extype: schoice
exsolution: 512
exshuffle: yes
expoints: 1
categories:
- vis
- '2023'
- schoice
date: '2023-02-26'
slug: diamonds-histogram
title: diamonds-histogram

---





```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 5,
                      fig.cap = "", 
                      fig.path = "",
                      dpi = 96,
                      out.width = "100%",
                      message = FALSE,
                      echo = FALSE)
```





# Aufgabe



Die Daten beziehen sich auf den Datensatz `diamonds` und sind [hier](https://ggplot2.tidyverse.org/reference/diamonds.html) einzusehen bzw. können bei Interesse dort heruntergeladen werden.

```{r message = FALSE, echo = FALSE}
data(diamonds, package = "ggplot2")
library(tidyverse)
library(plotly)


plot1 <- 
diamonds %>% 
  drop_na(cut, price) %>% 
  mutate(price = price/1000 %>% round) %>% 
  ggplot() +
  aes(x = price) +
  geom_histogram()  +
  geom_vline(aes(xintercept = median(price))) +
  theme_light() +
  facet_wrap( ~ cut, scales = "free")

ggplotly(plot1)
```


Answerlist
----------
* Auf der X-Achse ist eine nominalskalierte Variable abgetragen.
* Der vertikale Strich in jedem Bild passt gut zur Position des insgesamten Medians.
* Die Variable `cut` ist eine intervallskalierte Variable.
* Auf der x-Achse werden Häufigkeiten abgetragen.
* Die Gruppierungsvariable `cut` wird hier als ordinale Variable, also mit Ordnungsstruktur, verwendet.




</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung


Answerlist
----------
* Falsch
* Wahr
* Falsch
* Falsch
* Falsch






---

Categories: 

- vis
- '2023'
- schoice

