---
exname: wskt-quiz04
extype: schoice
exsolution: 1
exshuffle: no
categories:
- quiz
- probability
- distribution
- quiz1-qm2-ws23
- schoice
date: '2023-11-08'
slug: wskt-quiz04
title: wskt-quiz04

---




```{r global-knitr-options, include=FALSE, message=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = TRUE,  # ECHO IS FALSE!!!
                      message = FALSE,
                      fig.show = "hold")
```






# Aufgabe


Sei $X \sim Bin(10, 1/2)$. Dann ist die zugehörige Verteilung (von $X$) symmetrisch.

Hinweise:

- Orientieren Sie sich im Übrigen an den [allgemeinen Hinweisen des Datenwerks](https://datenwerk.netlify.app/hinweise).


Answerlist
----------

* Falsch
* Wahr


</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung


```{r}
x <- dbinom(x = 0:10, size = 10, prob = 1/2)

plot(x)
```

Symmetrisch!

Eine Binomialverteilung mit $p=1/2$ ist immer symmetrisch. (Bei $p\ne 1/2$ gilt das nicht.)



Answerlist
----------


* Falsch
* *Wahr*








---

Categories: 

- quiz
- probability
- distribution
- quiz1-qm2-ws23
- schoice

