---
exname: ziele-statistik
extype: schoice
exsolution: 1000
exshuffle: no
categories:
- basics
- '2023'
- schoice
date: '2023-02-01'
slug: Ziele-Statistik
title: Ziele-Statistik

---




```{r libs, include = FALSE}
library(tidyverse)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = TRUE,
                      message = FALSE,
                      fig.show = "hold")

```






# Aufgabe

Welche von den folgenden Optionen gehört *nicht* zu den Zielen von Statistik bzw. einer Forschungsfrage mit statistischem Character?


Answerlist
----------
* verstehen
* erklären
* vorhersagen
* beschreiben



</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung


Answerlist
----------

* Wahr
* Falsch
* Falsch
* Falsch






---

Categories: 

- - basics
- '2023'
- schoice

