---
extype: num
exsolution: r sol
exname: wertberechnen2
expoints: 1
extol: 0.2
categories:
- R
- dyn
- num
date: '2023-03-23'
slug: Wertberechnen2
title: Wertberechnen2

---



```{r libs, include = FALSE}

# library(tidyverse)
# library(mosaic)

```



```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```











# Aufgabe

```{r echo = FALSE}
startwert <- sample(c(0, 3, 8, 15, 24), size = 1)
x <- startwert
```

Welchen Wert bzw. welches Ergebnis liefert folgende R-Syntax für `ergebnis` zurück?

`x` hat zu Beginn den Wert `r x`. 

*Hinweise*: 

- `sqrt(x)` liefert die (positive) Quadratwurzel von `x` zurück.
- `x^2` liefert die zweite Potenz von `x` zurück.





```{r}
y <- 1

x <- x + y - 1

y = x

y <- y * 2

x <- x + 1

x <- sqrt(x)

ergebnis <- x^2
```



</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung



```{r echo = FALSE}
sol <- ergebnis
```

Es wird `r sol` zurückgeliefert.




---

Categories: 

- R
- dyn
- num

