---
# gleich diese Datei in einem Ordner mit Namen der Aufgabe abspeichern!
date: 2024-07-02
draft: true   # ACHTUNG DRAFT STEHT AUF TRUE!
title: kolmogorov  # HIER TITEL DES POSTS EINGEBEN.
execute: 
  eval: true 
highlight-style: arrow 
cache: true
toc: true
number-sections: true


categories:
- probability  # ENTER CATEGORIES HERE


bibliography: "../../library-ses.bib"

knitr:
  opts_chunk:
    out.width: "75%"

---





# Aufgabe 

Welche der folgenden Aussagen entspricht **NICHT** den Kolmogorov-Axiomen der Wahrscheinlichkeit?

A) P(A) ≥ 0 für jedes Ereignis A ∈ F

B) P(Ω) = 1 und P(∅) = 0

C) Wenn A ∩ B = ∅, dann ist P(A ∪ B) = P(A) + P(B)

D) P(A ∪ B) = P(A) + P(B) - P(A ∩ B) für beliebige Ereignisse A und B

E) P(A) kann negative Werte annehmen, wenn A ein sehr unwahrscheinliches Ereignis ist


Hinweise:


- Beachten Sie die üblichen [Hinweise](https://datenwerk.netlify.app/hinweise) des Datenwerks.


</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>











# Lösung 

**E**

**Antwort D** ist zwar nicht eines der drei Grundaxiome, aber eine korrekte Formel (Additionssatz), die aus den Axiomen abgeleitet werden kann.

- **Antwort E** verletzt das erste Kolmogorov-Axiom der Nichtnegativität. Wahrscheinlichkeiten können niemals negative Werte annehmen, unabhängig davon, wie unwahrscheinlich ein Ereignis ist. Die kleinste mögliche Wahrscheinlichkeit ist 0 (unmögliches Ereignis).

