---
exname: Verteilungen-Quiz-04
extype: schoice
exsolution: 1
exshuffle: no
categories:
- distributions
- Verteilungen-Quiz
- probability
- bayes
- simulation
date: '2022-11-20'
slug: Verteilungen-Quiz-04
title: Verteilungen-Quiz-04

---






```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = TRUE,
                      message = FALSE,
                      fig.show = "hold")



```






# Exercise

Ist folgende Aussage wahr?

Ist eine stetige Verteilung symmetrisch, dann ist sie normalverteilt.


Answerlist
----------
* Ja
* Nein



</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Solution

Nein, aber der Umkehrschluss gilt: Eine normalverteilte Zufallsvariable hat 
eine symmetrische Verteilungsform.

```{r echo = FALSE}
mosaic::xpnorm(0, 0, 1)
```



Answerlist
----------



* Falsch
* Wahr




---

Categories: 

- distributions
- Verteilungen-Quiz
- probability
- bayes
- simulation

