---
exname: wrangle5
extype: schoice
exsolution: 512
exshuffle: no
categories:
- eda
- '2023'
- schoice
date: '2023-03-27'
slug: wrangle5
title: wrangle5

---




```{r libs, include = FALSE}
library(tidyverse)
library(testthat)
library(glue)
library(printr)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```






# Aufgabe

Wie prüft man in R auf Gleichheit zweier Ausdrücke?

Wählen Sie die korrekte Aussage.






Answerlist
----------
* `!=` -- "definiert als"
* `==` Prüfung auf Gleichheit
* `=` -- Prüfung auf Gleichheit
* `<-` -- Prüfung auf Gleichheit
* `!=` -- Prüfung auf Gleichheit




</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung



S. [hier](https://r4ds.had.co.nz/transform.html#comparisons)

Answerlist
----------




* Falsch
* Wahr
* Falsch
* Falsch
* Falsch





---

Categories: 

- eda
- '2023'
- schoice

