---
exname: n-vars-diagram
extype: num
exsolution: r sol
exshuffle: no
expoints: 1
categories:
- vis
- '2023'
- num
date: '2023-02-26'
slug: n-vars-diagram
title: n-vars-diagram

---






```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      cache = TRUE,
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")

library(tidyverse)
```






# Aufgabe

Wie viele Variablen sind in folgendem Diagramm dargestellt?

Die Daten beziehen sich au den Datensatz `mtcars`; [hier](https://www.rdocumentation.org/packages/datasets/versions/3.6.2/topics/mtcars) finden Sie Informationen zu dem Datensatz. Er ist in R "fest eingebaut", also direkt verfügbar.





</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung


```{r}
mtcars %>% 
  ggplot(aes(x = hp, y = mpg, color = factor(am), size = cyl)) +
  geom_point() +
  facet_wrap(~vs)
```

Es sind 5 Variablen abgebildet:

- hp
- mpg
- am
- cyl
- vs

```{r}
sol <- 5
```




---

Categories: 

- vis
- '2023'
- num

