---
date: 2024-01-12  # HEUTIGES DATUM EINTRAGEN
draft: FALSE   # ACHTUNG DRAFT STEHT AUF TRUE!
title: Kausal # ACHTUNG: HIER NAMEN DER AUFGABE ANGEBEN

execute: 
  eval: true 
  
highlight-style: arrow 
cache: true


extype: string
exsolution: ""
exshuffle: no
categories:
- causal  # ENTER CATEGORIES HERE

---





<!-- The author of this question is Karsten Lübke. -->


```{r data generation, echo = FALSE, results = "hide"}
library(exams)

pfeil <- sample(c("A hängt ab von B", "B hängt ab von A"),1)
uv <- sample(c("A", "B"),1)
cv <- ifelse(uv=="A", "B", "A")

## Questions
questions <- character(7)
questions[1] <- "`C ~ A`"
questions[2] <- "`C ~ B`"
questions[3] <- "`C ~ A + B`"
questions[4] <- paste0("`", uv, " ~ C`")
questions[5] <- paste0("`", uv, " ~ C + ",  cv, "`")
questions[6] <- paste0("`", uv, " ~ ",  cv, "`")
questions[7] <- "Der totale kausale Effekt kann nicht bestimmt werden."


solutions <- rep(FALSE, 7)

if (uv=="A") {
  if (pfeil == "A hängt ab von B") solutions[3] <- TRUE
  else solutions[1] <- TRUE
}

if (uv=="B") {
  if (pfeil == "A hängt ab von B") solutions[2] <- TRUE
  else solutions[3] <- TRUE
}


```

# Aufgabe
  
Die kausale Abhängigkeit zwischen drei Variablen A, B, C sieht wie folgt aus:

- `r pfeil`.
- C hängt ab von A.
- C hängt ab von B.

Hinweise:

- Abhängigkeit ist kausal zu verstehen.


*Aufgabe:* **Wie lautet die R-Formel, um den totalen kausalen Effekt von `r uv` auf C zu bestimmen?**
  
```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```


# Lösung


---

Aufgaben-ID: Kausal

Der Autor dieser Aufgabe ist Karsten Lübke.

---



```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(ifelse(solutions, "Richtig", "Falsch"), markup = "markdown")
```

