---
extype: schoice
exsolution: 1
exname: breiman
categories:
- ds1
- prediction
- statlearning
- schoice
date: '2023-05-17'
slug: breiman
title: breiman

---





# Aufgabe

In einem berühmten Paper mit dem Titel "Statistical Modeling: The Two Culture" hat Leo Breiman zwei Arten der Datenanalyse vorgestellt und kritisch diskutiert. 
Dieser Artikel wurde vielfach diskutiert, weil er zentrale Fragen des Fachgebiets anstieß bzw. intensivierte. 
Welche der folgenden Kontroversen zeichnen das Feld der Datenanalyse *nicht*?

Welche Aussagen sind in diesem Zusammenhang *falsch*?

Answerlist
----------

* Zentrale Fragestellungen der Datenanalyse kann man mit den Zielen *Vorhersage* und *Erklärung* (des Kausalmodells) kontrastierend vorstellen.
* Man kann zwei "Lager" oder Fraktionen innerhalb der Datenanalyse ausmachen: Die mehr an Mathematik orientierten Statistiker und die mehr an Informatik orientierten Datenwissenschaftler.
* Statistische Modelle (bzw. die Modelle der Statistiker) basieren auf der Wahrscheinlichkeitsrechnung.
* Die Modelle der Datenwissenschaftler bezeichnet man auch als algorithmische Modelle.
* Die Modelle der Datenwissenschaftler sind zumeist "Black-Box-Modelle".
* Ein Beispiel für ein Black-Box-Modell ist die klassische Regression (Methode der kleinsten Quadrate).





</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung

*Falsch*: Ab einer Größe von $n=30$ sind Stichproben robust und ausreichend präzise Schätzer für den gesuchten Populationsparameter.




---

Categories: 

- ds1
- prediction
- statlearning
- schoice

