---
# gleich diese Datei in einem Ordner mit Namen der Aufgabe abspeichern!
date: 2024-07-02
draft: true   # ACHTUNG DRAFT STEHT AUF TRUE!
title: def-nullhyp  # HIER TITEL DES POSTS EINGEBEN.
execute: 
  eval: true 
highlight-style: arrow 
cache: true
toc: true
number-sections: true


categories:
- inference  # ENTER CATEGORIES HERE


bibliography: "../../library-ses.bib"

knitr:
  opts_chunk:
    out.width: "75%"

---





# Aufgabe 

Welche Aussage zur *Nullhypothese* ist korrekt?


Die Nullhypothese ist ...


A) Die Hypothese, die besagt, dass zwischen den untersuchten Variablen ein starker Zusammenhang besteht.
B) Die Hypothese, die einen Effekt, Unterschied oder Zusammenhang postuliert und die der Forscher zu beweisen versucht.
C) Die Hypothese, die besagt, dass kein Effekt, kein Unterschied oder kein Zusammenhang zwischen den untersuchten Variablen besteht.
D) Die Hypothese, die automatisch angenommen wird, wenn die Alternativhypothese verworfen wird.
E) Die Hypothese, die die erwarteten Ergebnisse der Studie vorhersagt und immer beibehalten wird.
F) Die Hypothese, die nur bei einseitigen Tests verwendet wird und die Richtung des Effekts spezifiziert.



Hinweise:


- Beachten Sie die üblichen [Hinweise](https://datenwerk.netlify.app/hinweise) des Datenwerks.


</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>











# Lösung 


**C**
Die Nullhypothese (H₀) ist die Annahme, dass kein Effekt, Unterschied oder Zusammenhang vorliegt. Sie wird als Ausgangspunkt für statistische Tests verwendet und kann entweder beibehalten oder verworfen werden, basierend auf den empirischen Daten. Mit neueren Ansätzen wir dem ROPE-Konzept kann eine "Rope-Nullhypothese" auch bestätigt werden.



