---
exname: wrangle3
extype: schoice
exsolution: 8
exshuffle: no
categories:
- datawrangling
- eda
- schoice
date: '2023-03-27'
slug: wrangle3
title: wrangle3

---




```{r libs, include = FALSE}
library(tidyverse)
library(testthat)
library(glue)
library(printr)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```






# Aufgabe



Welche Aussage zu der Funktionsweise folgender Funktionen im R-Paket `dplyr` ist richtig?


- filter
- select
- summarise
- count
- group_by


Answerlist
----------
* Das erste Argument darf nie ein Dataframe sein.
* Das erste Argument ist immer die zu analysierende Variable.
* Spaltennamen müssen mit Anführungsstrichen benannt werden.
* Es wird immer eine Tabelle ausgegeben.
* Funktionsnamen sind (zumeist) *nicht* als Verben formuliert.



</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung



S. [hier](https://r4ds.had.co.nz/transform.html#dplyr-basics)

Answerlist
----------




* Falsch
* Falsch
* Falsch
* Wahr
* Falsch





---

Categories: 

- datawrangling
- eda
- schoice

