---
extype: string
exsolution: NA
exname: stichprobenziehen1
expoints: 1
categories:
- lm
- inference
- qm2
date: '2022-09-04'
slug: Stichprobenziehen1
title: Stichprobenziehen1

---






# Exercise

In dieser Übung untersuchen wir den Effekt der Stichprobengröße auf die Genauigkeit der Schätzung. 
Und zwar auf praktische Art und Weise.

Als praktisches Beispiel soll uns dabei die Körpergröße dienen. 
Wir erfragen die Körpergröße der Studis und betrachten den Mittelwert einer Stichrpobe in Abhängigkeit der Größe der Stichprobe.

1. Geben Sie anonym Ihre Körpergröße [hier](https://docs.google.com/forms/d/e/1FAIpQLSfOXrpymPxrBHsrLGeXqgFNiYjInojcXYfpGT6_Z9DLhmi1rA/viewform?usp=sf_link) ein.
2. Sie können die Daten [hier](https://docs.google.com/spreadsheets/d/11jnVSgVbz280E7oFHgQQP-G-QghlWV9CLl9ykDnfjwc/edit?usp=sharing) beziehen.
3. Berechnen Sie den Mittelwert der Körpergröße für eine zufällige Stichprobe der Größen $n=5$ und $n=50$ 
4. Dann berechnen Sie die den "echten" Mittelwert der Studis; damit ist der Mittelwert aller Werte der Tabelle gemeint.
5. Diskutieren Sie die Ergebnisse!
6. Wird die Schätzung genauer bei größerer Stichprobe?
7. Wird die Schätzung "robuster" (weniger schwankend) bei größerer Stichprobe?





</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Solution

Individuell



---

Categories: 

- lm
- inference
- qm2

