---
# gleich diese Datei in einem Ordner mit Namen der Aufgabe abspeichern!
date: 2025-10-17
draft: false   # ACHTUNG DRAFT STEHT AUF TRUE!
title: xls-online-import  # HIER TITEL DES POSTS EINGEBEN.
execute: 
  eval: true 
highlight-style: arrow 
cache: true
toc: true
number-sections: true


categories:
- data
- datawrangling # ENTER CATEGORIES HERE


bibliography: "../../library-ses.bib"

knitr:
  opts_chunk:
    out.width: "75%"

---





# Aufgabe 

Importieren Sie eine XLSX-Datei aus dem Internet in R (als Dataframe).


Hier ist ein Pfad: <https://github.com/sebastiansauer/Lehre/raw/refs/heads/main/25-SoSe/FAU-2025-09/penguins.xlsx>.

```{r}
data_url <- "https://github.com/sebastiansauer/Lehre/raw/refs/heads/main/25-SoSe/FAU-2025-09/penguins.xlsx"
```


Hinweise:


- Beachten Sie die üblichen [Hinweise](https://datenwerk.netlify.app/hinweise) des Datenwerks.


</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>

</br>
</br>
</br>











# Lösung 


## Weg 1

```{r}
library(rio)
penguins <- import(data_url)
```


## Weg 2

```{r}
#| error: true
#| eval: false

dest_file <- "penguins.xlsx"

download.file(url = data_url, destfile = dest_file, mode = "wb")

library(readxl)

my_data <- read_excel(dest_file)
```

