---
exname: argumente
extype: schoice
exsolution: 1
exshuffle: no
categories:
- R
- '2023'
- schoice
date: '2023-03-23'
slug: argumente
title: argumente

---




```{r libs, include = FALSE}
library(tidyverse)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = TRUE,
                      message = FALSE,
                      fig.show = "hold")

```






# Aufgabe

Welche der folgenden Syntax-Beispiele zeigt *fehlerhaften* Code? 

Es sei jeweils definiert:

```{r}
x <- c(1, 2, 3)
```







Answerlist
----------
* `mean(x = x)`
* `mean(FALSE)`
* `mean(na.rm = FALSE, x = x)`
* `mean(x, 0, FALSE)`




</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung



Answerlist
----------


* Falsch
* Wahr
* Falsch
* Falsch





---

Categories: 

- R
- '2023'
- schoice

