---
exname: wrangle7
extype: schoice
exsolution: 10000
exshuffle: no
categories:
- eda
- '2023'
- schoice
date: '2023-02-08'
slug: wrangle7
title: wrangle7

---




```{r libs, include = FALSE}
library(tidyverse)
library(testthat)
library(glue)
library(printr)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```






# Aufgabe

Welche Aussage zur Funktion `filter()` aus dem R-Paket `dplyr` ist richtig?





Answerlist
----------
* `filter()` filtert (behält) Zeilen, für die eine Prüfung `TRUE` ergibt
* `filter()` filtert (behält)Zeilen, für die eine Prüfung `FALSE` ergibt
* `filter()` filtert (behält) Zeilen, für die eine Prüfung `TRUE` oder `NA` ergibt 
* Möchte man nur nicht-fehlende Zeilen aus der Variable `x` aus dem Dataframe `df` filtern (behalten), so formuliert man `filter(df, x == NA)`.
* Möchte man nur nicht-fehlende Zeilen aus der Variable `x` aus dem Dataframe `df` filtern (behalten), so formuliert man `filter(df, is.na(x))`.




</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung

S. [hier](https://r4ds.had.co.nz/transform.html#missing-values)


Answerlist
----------



* Wahr
* Falsch
* Falsch
* Falsch
* Falsch





---

Categories: 

- eda
- '2023'
- schoice

