---
exname: max-corr1
extype: num
exsolution: r fmt(sol)
exshuffle: no
expoints: 1
categories:
- vis
- '2023'
- num
date: '2023-02-26'
slug: max-corr1
title: max-corr1

---






```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      cache = TRUE,
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")

library(tidyverse)
library(exams)
```






# Aufgabe

Welches Diagramm zeigt den stärksten (absoluten) linearen Zusammenhang (Korrelation)?

Geben Sie die Nummer ein, die in der Kopfzeile jedes Teildiagramms angezeigt wird.


</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung

```{r}
d_path <- "https://raw.githubusercontent.com/sebastiansauer/pradadata/master/data-raw/corr_data.csv"
d <- read.csv(d_path)

d %>% 
  filter(correlation > 0) %>% 
  ggplot(aes(V1, V2)) +
  geom_point() +
  stat_ellipse(level = .999, type = "norm", color = "blue", alpha = .5) +
  facet_wrap(~ id_cor)
```



```{r}
sol <- 9
```






---

Categories: 

- vis
- '2023'
- num

